#!/bin/bash

#

[ -f /news2.tar.gz -a -f /olds2 ] || exit 1

#

if [ `find /usr/local -name 'struts2-core-2.2.3.jar' | wc -l` -gt 0 ]; then
   # get tomcats
   Htomcats=`find /usr/local -name 'struts2-core-2.2.3.jar' | sed -re "s/(.*)(tomcat[0-9a-zA-Z]+).*/\2/" | sort | uniq`

   # stop tomcats
   echo "$Htomcats" | sed -re "s/(.*)/\/root\/mode\/stop_tomcat \1/" | bash

   # add new jars
   find /usr/local -name 'struts2-core-2.*jar' | sed -re "s/(.*\/).*/cd \1;tar xzvf \/news2.tar.gz/" | bash

   # delete old jars 
   find /usr/local -name 'struts2-core-2.*jar' | sed -re "s/(.*\/).*/cd \1;rm -f \`cat \/olds2\`/" | bash

   # start tomcats
   echo "$Htomcats" | sed -re "s/(.*)/\/root\/mode\/start_tomcat \1/"  | bash
fi


