#!/bin/bash
# ===============================================
# Function:
#    
# Date:
#   :
# ===============================================
#
#. /root/imode/cfg/.imode_aliases
#
for i in `cat /root/zhangh/sshcodes.txt | grep -v "^#" | grep -E "^${1:-.*}$"`; do
  echo $i
  #scp -4 -l 8192 -p /mode.tar.gz $i:/ && ssh -4 $i "echo 'starting...';cd /;tar xzvf mode.tar.gz >/dev/null 2>&1;echo ok" 2>/dev/null
done
