#!/bin/bash
# ===============================================
# Function:
#   do while all sshcodes Demo
# Date:
#   :2015-04-27
# ===============================================
shopt -s expand_aliases
alias ssh='ssh -q'

for i in `cat /root/zhangh/sshcodes.txt | grep -v "^#" | grep -E "^${1:-.*}$"`; do
  echo
  echo "=================== Server $i ===================="
  echo
  ssh $i $2
done
