#!/bin/bash
# ===================================================
# Function:
#			Judge same progress
# Date:		
#			2015-01-28
# ===================================================

Hpps=$1
Hextra=$(ps -eo pid,ppid,cmd|
			grep -E "^ *[0-9]+ +[0-9]+ +/bin/bash +[^ ]*/$2" |
			grep -E -v "^ *($Hpps +[0-9]+|[0-9]+ +$Hpps) +/bin/bash +[^ ]*/$2" | wc -l)

if [ $Hextra -gt 0 ]; then
	exit 0
fi

exit 1
