#!/bin/bash
# ===============================================
# Function:
#     install mysql-connector-python
# Date:
#     2017-2-18
# ===============================================


tar zxvf /root/zhangh/hpackages/mysql-connector-python-2.2.2.tar.gz

cd /root/zhangh/hpackages/mysql-connector-python-2.2.2

python setup.py install


if [-f /usr/local/lib/python2.7/site-packages/mysql_connector_python-2.2.2-py2.7.egg-info ]; then
  echo "install success!!!" && exit 0
else
  echo "install failed!!" && exit 1
fi
