#!/bin/bash
# =====================================================================================
# Function:
#			copy standard dump from remote server to local /root/zhangh/dump directory
# Usage	  :
# 			./scpdump <remote-server-name> <dbname> <dumpdir>
# =====================================================================================

if [ -z "$1" ];then
	/root/zhangh/hmsg scpdump "Please provide remote server name" more
    exit
fi

if echo "$1" | grep "root" > /dev/null; then
  Hcode=`echo "$1" | sed -e "s/root@//"`
fi

# check remote server code<ssh code>

if ! cat /root/zhangh/sshcodes.txt 2>/dev/null | grep -E "^$Hcode$" >/dev/null; then 
	/root/zhangh/hmsg scpdump "Remote server name must be registered first!" more
	exit
fi
# check stardard mysql database name
if [ -z "$2" ];then
	/root/zhangh/hmsg scpdump "Database name must be provided" more
	exit
fi

dumpname=`ssh $1 "ls -1 /root/mode/dump/$2-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9][0-9].sql 2>/dev/null | sed -n '$ p'"`

if [ -z "$dumpname" ];then
	/root/zhangh/hmsg scpdump "No standard dump of '$2' exists in remote server '$Hcode'" more
	exit
fi


if [ -z "$3" ]; then
	dumpdir=/root/zhangh/dump
elif [ -d "$3" ];then
	dumpdir="$3"
else
	/root/zhangh/hmsg scpdump "Please right dirname must be provided!!!" more
	exit 1
fi


scp -Cp "$1":"$dumpname" "$dumpdir" 


# remove history dumps

datedel=`date -d "-7 day" +"%Y-%m-%d"`

rm -f /root/zhangh/dump/"$2"-"$datedel"_[0-9][0-9][0-9].sql 2>/dev/null

