INSERT INTO pos_func VALUES (	'check',	'f_change_dish',	'DISH切换. 参数:1-合计;2-汇总;3-明细',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_input_amount',	'输入付款',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_card',	'信用卡付款',	'_com_Touch信用卡付款;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and deptno in (''C'',''D'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_cardin',	'信用卡内卡付款',	'_com_Touch信用卡付款;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and deptno in (''C'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_cardout',	'信用卡外卡付款',	'_com_Touch信用卡付款;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and deptno in (''D'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_cash',	'现金付款',	'_com_Touch现金付款;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and deptno in (''A'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_cheque',	'支票付款',	'_com_Touch支票付款;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and  deptno in (''B'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N', ' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_dscent',	'款待,折扣','_com_Touch款待折扣;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and  deptno in (''H'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_other',	'其他付款方式',	'_com_Touch其他付款方式;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9''  order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_toa',	'转前台',	'_com_Touch转前台;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and deptno in (''I'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_paymth_tor',	'转AR',	'_com_Touch转AR;(select char10  =  pccode,descript,descript1 from pccode where pccode>''9'' and deptno in (''J'') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_check_show_funclist',	'显示功能列表',	'',	'N',	' ');
INSERT INTO pos_func VALUES (	'check',	'f_check_show_paylist',	'显示付款方式',	'',	'N',	' ');
INSERT INTO pos_func VALUES (	'dish_cond',	'f_con_item_slu',	'配料',	'_com_Touch配料;(select code,descript from pos_condgp where flag ="P" order by code);code:代码;descript:描述=20',	'N',	'');
INSERT INTO pos_func VALUES (	'dish_cond',	'f_confirm',	'确定退出',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'dish_cond',	'f_del_dtl',	'取消明细',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'dish_cond',	'f_helpcode',	'助记码',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'dish_cond',	'f_number',	'修改数量',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_front_list',	'查询前台客人和消费账信息',	' ',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_guest_list',	'查询客人档案信息',	' ',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_armst_list',	'查询ＡＲ账信息',	' ',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_cusno_list',	'查询公司档案信息',	' ',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_plu_assess',	'查询估清',	'估清;(select a.id,b.code,b.name1,b.name2,a.unit,a.number,a.number1,a.number2,a.payout from pos_assess a,pos_plu b where a.id = b.id order by b.code);a.id:序号=5;b.code:菜号=6;b.name1:菜名=20;b.name2:英文=20;a.unit:单位;a.number:数量=4;a.number1:已用数量=4;a.number2:调整数量=4;a.payout:售完',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_plu_flag4',	'查询推荐菜',	'查询推荐;(select code,id,name1,name2 from pos_plu where flag4 ='T');code:菜号;id:序号=5;name1:名称=20;name2:英文=20',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_plu_flag6',	'查询锁菜',	'锁菜;(select code,id,name1,name2 from pos_plu where flag6 ='T');code:菜号;id:序号=5;name1:名称=20;name2:英文=20',	'N',	'');
INSERT INTO pos_func VALUES (	'info',	'f_reserve_list',	'查询预定信息',	' ',	'N',	'');
INSERT INTO pos_func VALUES (	'login',	'f_login',	'进入系统',	' ',	'Y',	'进入餐位图或开单窗口');
INSERT INTO pos_func VALUES (	'login',	'f_shift',	'输入班号',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'login',	'f_show_shift',	'显示班别',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'map',	'f_set_assess',	'设置沽清单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'map',	'f_set_quick_sale',	'设置推荐菜',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'map',	'f_tableno',	'点选桌号,预定转登记或开台或进入点菜',	'_com_Touch桌号选择;(select char10  =  a.pccode + ''&'' + a.tableno,a.descript1,b.descript from pos_tblsta a, pos_pccode b where a.pccode=b.pccode order by a.pccode,a.tableno);char10:代码;a.descript1:描述=20;b.descript:餐厅',	'Y',	'进入点菜窗口');
INSERT INTO pos_func VALUES (	'menu_list',	'f_checkout',	'进入结帐',	' ',	'Y',	'进入结帐窗口');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_bill',	'帐单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_dtl',	'查看餐单明细',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_guests',	'输入人数',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_jion',	'并单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_new',	'临时台开新单',	' ',	'Y',	'进入点菜窗口');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_one',	'是否为独单操作模式',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_order',	'进入点菜',	' ',	'Y',	'进入点菜窗口');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_split',	'分单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_tableno',	'输入台号',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_menu_unjion','撤销并单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_other_shift',	'显示其他班别餐单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_recheck',	'重结',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_search_table',	'按桌号查找',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_select_pccode',	'选择餐厅',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_show_checked',	'显示已结帐餐单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_turn_shift',	'接班',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'menu_list',	'f_buffer_clear',	'清空输入缓冲区',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_add_number',	'点菜落单前增加数量:参数为负就是减数量',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_checkout',	'结帐',	' ',	'Y',	'进入结帐窗口');
INSERT INTO pos_func VALUES (	'order',	'f_del_order',	'点菜取消',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_dish_rename',	'改菜名',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'order',	'f_helpcode',	'助记码',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_kitchen_callup',	'叫起',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'order',	'f_kitchen_print',	'厨打指令',	'',	'N',	'');
INSERT INTO pos_func VALUES ( 'order',	'f_kitchen_quick',	'催菜',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'order',	'f_kitchen_slow',	'缓菜',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'order',	'f_kitchen_updish',	'起菜',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'order',	'f_lock_plu',	'锁菜',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_menu_order_new',	'同台开新单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_menu_cancel',	'消单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_menu_guests',	'人数',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_menu_change',	'换单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_menu_tableno',	'换台',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_order_back',	'退菜',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_order_jion',	'配菜影响菜价',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_order_plucode',	'点击大类',	'_com_点菜大类;(select plucode,descript from pos_plucode  order by plucode);plucode:代码;descript:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_order_std_mst',	'套菜',	'_com_Touch点菜分类;(select code,descript from basecode where cat=''touch_sort'' order by code);code:代码;descript:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_order_to_dish',	'落单',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_order_unit',	'根据菜的计量单位定位单价',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_plu_item_slu',	'菜谱查询定位',	'_com_Touch点菜;(select char10  =  convert(char(10),  a.id), a.name1, b.descript, c.name1, a.code from pos_plu a, pos_plucode b, pos_sort c where a.plucode = b.plucode and a.sort = c.sort and b.plucode = c.plucode and a.pluid = b.pluid order by a.plucode,a.sort,a.code);char10:代码;a.name1:菜名;b.descript:大类;c.name1:小类=20;a.code:菜号',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_set_siteno',	'点菜设置客位',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_show_func_more',	'显示附加功能',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_plu_pic_order',	'显示菜的图片并点菜',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_siteno_func',	'餐位排布',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'order',	'f_check_msg_input',	'结账信息输入',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_check_suspend',	'挂账,释放餐位资源sta=4',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_close',	'Close',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_cond_item_slu',	'烹饪配料',	'_com_Touch烹饪要求;(select code,descript from pos_condgp where flag="P" order by code);code:代码;descript:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_cond_item_open',	'打开配料窗口',	'_com_Touch烹饪要求;(select code,descript from pos_condgp order by code);code:代码;descript:描述=20',	'Y',	'进入配料窗口');
INSERT INTO pos_func VALUES (	'system',	'f_cook_item_slu',	'烹饪要求',	'_com_Touch烹饪要求;(select code,descript from pos_condgp where flag <>"P" order by code);code:代码;descript:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_dish_co',	'冲菜',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_dish_dsc',	'单菜折扣',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_dish_ent',	'单菜款待',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_dish_nofee',	'单菜免',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_dish_nosrv',	'免服务费',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_dish_number',	'改数量',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_dish_price',	'改单价',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_dish_reward',	'赠送',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_exit',	'退出系统',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_fresh',	'刷新',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_input_char',	'输入字符串',	' ','N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_input_clear',	'清空缓冲区',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_menu_bill',	'打印帐单',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_menu_dsc_rate',	'折扣费率',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_menu_mode',	'模式',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_menu_room',	'客房送餐',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_menu_srv_rate',	'服务费率',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_menu_tea',	'茶位费',	'',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_open',	'Open',	' ','Y',	'进入指定窗口');
INSERT INTO pos_func VALUES (	'system',	'f_pagedown',	'下翻',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_pageup',	'上翻',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_paymth_cash',	'现金付款',	'_com_Touch现金付款;(select char10  =  pccode,descript,descript1 from pccode where pccode>'9' and deptno in ('A') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_paymth_toa',	'转前台',	'_com_Touch转前台;(select char10  =  pccode,descript,descript1 from pccode where pccode>'9' and deptno in ('I') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_paymth_tor',	'转AR',	'_com_Touch转AR;(select char10  =  pccode,descript,descript1 from pccode where pccode>'9' and deptno in ('J') order by pccode);char10:代码;descript:描述=20;descript1:描述=20',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_return',	'退出并返回某个窗口',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_set_layout',	'设置输入法',	' ',	'N',	'');
INSERT INTO pos_func VALUES (	'system',	'f_set_password',	'设置密码',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_setnull',	'设置空缺所设对象暂时没有功能',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_shiftrep',	'交班表',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_shutdown',	'关机',	' ',	'N',	' ');
INSERT INTO pos_func VALUES (	'system',	'f_time',	'显示时间',	' ',	'N',	' ');
