#!/bin/bash
# --------------------------------------------------------------------------------
# function:
#           clear linux caches etc. 
# e.g.    :
#          ./clrcache       # conventional call  
#          ./clrcache 1     # might do more thing than conventional call
# --------------------------------------------------------------------------------

# check authority 

if [ "$HOME" != "/root" -a "$HOME" != "/" ]; then
   exit 1
fi

# check linux version  

if [ -x /etc/ifconfig ]; then
   exit 0
fi

# new method to check reentrance 

/root/mode/withyou $$ clrcache 1 && exit 

# 

/root/mode/.pis 

# collect data 

HFREE=`free`
HTTLMEM=`echo "$HFREE"  | grep "Mem:"  | sed -e "s/^Mem: *\([0-9]\{1,\}\).*/\1/"`
HTTLSWP=`echo "$HFREE"  | grep "Swap:" | awk '{print $2}'`
HUSED1=`echo "$HFREE"   | grep "Mem:"  | sed -re "s/^Mem: *([0-9]+) *([0-9]+).*/\2/"`
HUSED2=`echo "$HFREE"   | grep "buffers/cache:" | sed -re "s/.*buffers\/cache: *([0-9]+).*/\1/"`
HUSED3=`echo "$HFREE"   | grep "Swap:" | sed -re "s/^Swap: *([0-9]+) *([0-9]+).*/\2/"`
HUSED1PT=`echo "$HUSED1 * 100 / $HTTLMEM" | bc`
HUSED2PT=`echo "$HUSED2 * 100 / $HTTLMEM" | bc`
HUSED3PT=`echo "($HUSED2+$HUSED3) * 100 / $HTTLMEM" | bc`
HUSED4PT=`echo "($HUSED1-$HUSED2) * 100 / $HTTLMEM" | bc`

#

sysctl -w vm.dirty_writeback_centisecs=300 &>/dev/null
sysctl -w vm.dirty_expire_centisecs=1800   &>/dev/null
sysctl -w vm.dirty_background_ratio=10     &>/dev/null 
sysctl -w vm.dirty_ratio=90                &>/dev/null
if [ $HTTLSWP -gt 0 ]; then
   Hmin_free=20480
else
   Hmin_free=10240
fi
if [ $HUSED2PT -lt 92 -a $HUSED3 -eq 0 ]; then
   Hmin_free=$[$HTTLMEM*1/100]
fi
if [ $Hmin_free -ge 102400 ]; then
   Hmin_free=102400
fi
sysctl -w vm.min_free_kbytes=$Hmin_free    &>/dev/null
sysctl -w vm.vfs_cache_pressure=100        &>/dev/null

# 

if [ $HUSED3 -le 0 ]; then

   # swap has not been used or no swap partitions 

   if [ $HTTLSWP -eq 0 -a $HUSED2PT -ge 95 ]; then
      # display warning 
      if [ $HUSED2PT -ge 97 ]; then
         /root/mode/modemsg clrcache "No sufficient memory for the workload!!!extremely high memory load!!!"
         /root/mode/modemsg clrcache "Please add system memory as soon as possible!!!" more
      else
         /root/mode/modemsg clrcache "No sufficient memory for the workload!!!extra high memory load!!!" more
      fi
   fi
   #
   if /root/mode/.ps_exit .mc1_pschk; then
      # .ps_exit has priority over "$1" check
      exit
   elif [ -n "$1" ]; then
      # "$1" has priority over $HUSED1PT check 
      if [ -f /etc/.mc1_pschk ]; then
         /root/mode/modemsg clrcache "pforce:drop_cache task began at `LANG=en_US;date`"
         echo 3 > /proc/sys/vm/drop_caches
         /root/mode/modemsg clrcache "pforce:drop_cache task ended at `LANG=en_US;date`" more
      else
         echo 3 > /proc/sys/vm/drop_caches
      fi
   elif [ $HUSED2PT -ge 95 ]; then
      # -----------------------------------------------------------
      # extra high usage of memory,always drop buffers/caches
      # -----------------------------------------------------------
      # important:we use $HUSED2PT instead of $HUSED1PT
      # -----------------------------------------------------------
      if [ -f /etc/.mc1_pschk ]; then
         /root/mode/modemsg clrcache "pb$HUSED2PT:drop_cache task began at `LANG=en_US;date`"
         echo 3 > /proc/sys/vm/drop_caches
         /root/mode/modemsg clrcache "pb$HUSED2PT:drop_cache task ended at `LANG=en_US;date`" more
      else
         echo 3 > /proc/sys/vm/drop_caches
      fi
   elif [ $HUSED1PT -ge 92 ]; then
      # -----------------------------------------------------------
      # rather high usage of memory,drop buffers/caches more often
      # -----------------------------------------------------------
      if [ $HUSED4PT -ge 1 ]; then
         if [ -f /etc/.mc1_pschk ]; then
            /root/mode/modemsg clrcache "p$HUSED1PT:drop_cache task began at `LANG=en_US;date`"
            echo 3 > /proc/sys/vm/drop_caches
            /root/mode/modemsg clrcache "p$HUSED1PT:drop_cache task ended at `LANG=en_US;date`" more
         else
            echo 3 > /proc/sys/vm/drop_caches
         fi
      fi
   elif [ $HUSED1PT -ge 88 ]; then
      # ------------------------------------------
      # drop buffers/caches at large scale 
      # ------------------------------------------
      if [ $HUSED4PT -ge 3 ]; then
         if [ -f /etc/.mc1_pschk ]; then
            /root/mode/modemsg clrcache "p$HUSED1PT:drop_cache task began at `LANG=en_US;date`"
            echo 3 > /proc/sys/vm/drop_caches
            /root/mode/modemsg clrcache "p$HUSED1PT:drop_cache task ended at `LANG=en_US;date`" more
         else
            echo 3 > /proc/sys/vm/drop_caches
         fi
      fi
   else
      exit
   fi
else
   if /root/mode/.ps_exit .mc2_pschk; then
      exit 
   fi
   /root/mode/modemsg clrcache "s:drop_cache task began at `LANG=en_US;date`"
   echo 3 > /proc/sys/vm/drop_caches
   /root/mode/modemsg clrcache "s:drop_cache task ended at `LANG=en_US;date`"
   if [ $HUSED3PT -le 96 ]; then
      # clear caches & buffers
      /root/mode/modemsg clrcache "le$HUSED3PT task began at `LANG=en_US;date`"
      if sync; then
         /root/mode/modemsg clrcache "sync part ended at `LANG=en_US;date`"
         echo 3 > /proc/sys/vm/drop_caches
         /root/mode/modemsg clrcache "drop part ended at `LANG=en_US;date`"
         # clear swap
         /sbin/swapoff -a && /sbin/swapon -a
         /root/mode/modemsg clrcache "swap part ended at `LANG=en_US;date`" more
      else
         /root/mode/modemsg clrcache "No sufficient memory for the workload!!!" more
      fi
   elif [ $HUSED3PT -le 99 ]; then
      # -------------------------------------------------------------------------------
      # I don't know if 'swapoff -a' will succeed
      # System administrator should stop some services,then restart them to free memory 
      # -------------------------------------------------------------------------------
      /root/mode/modemsg clrcache "No sufficient memory for the workload!!!" more
   else
      # -------------------------------------------------------------------------------
      # situation:  memory stress
      # suggestion: add system memory
      # -------------------------------------------------------------------------------
      /root/mode/modemsg clrcache "No sufficient memory for the workload!!!"
      /root/mode/modemsg clrcache "Please add system memory as soon as possible!!!" more
   fi
fi

# end of script

