#!/bin/bash
# -------------------------------------------
# function:
# -------------------------------------------

# exclusive execution with wait mode

/root/mode/modepv config_sshd $$ " /bin/bash .*/config_sshd"

# change order of sshd

if [ -f /etc/init.d/sshd ]; then
   cat /etc/init.d/sshd | sed -re "s/^(# chkconfig: 2345).*/\1 28 72/" > /root/mode/tmp/Hmodsshd$$.tmp
   if ! cmp /etc/init.d/sshd /root/mode/tmp/Hmodsshd$$.tmp &>/dev/null; then
      cp -f /root/mode/tmp/Hmodsshd$$.tmp /etc/init.d/sshd
      chmod u+x /etc/init.d/sshd
   fi
   rm -f /root/mode/tmp/Hmodsshd$$.tmp
   # force to rechkconfig
   chkconfig sshd on
fi

# using mod_config

/root/mode/mod_config /etc/ssh/sshd_config "TCPKeepAlive yes"          "#TCPKeepAlive"
/root/mode/mod_config /etc/ssh/sshd_config "LoginGraceTime 0"          "#LoginGraceTime"
/root/mode/mod_config /etc/ssh/sshd_config "ClientAliveInterval 10"    "#ClientAliveInterval"
/root/mode/mod_config /etc/ssh/sshd_config "ClientAliveCountMax 10"    "#ClientAliveCountMax"
/root/mode/mod_config /etc/ssh/sshd_config "UseDNS no"                 "#UseDNS"

# using rep_config

/root/mode/rep_config /etc/ssh/sshd_config "ListenAddress ::"          "comment"
/root/mode/rep_config /etc/ssh/sshd_config "ListenAddress 0.0.0.0"     "uncomment"

# ------------------------------------------------------------------------------------------------------------------------------
# In aliyun computers with CentOS 6.5,the 'AddressFamily inet' option was wrongly placed so that startup failure of sshd service
# may happen
# ------------------------------------------------------------------------------------------------------------------------------
# 'AddressFamily inet' must be placed before 'ListenAddress' to avoid conflict with our 'ListenAddress 0.0.0.0'
# ------------------------------------------------------------------------------------------------------------------------------
# We simply commented out 'AddressFamily inet' option wrongly placed by Ali                                     -- 2014-10-13 --
# ------------------------------------------------------------------------------------------------------------------------------
/root/mode/rep_config /etc/ssh/sshd_config "AddressFamily inet"        "comment"

/root/mode/rep_config /etc/ssh/sshd_config "Protocol 2,1"              "comment"
/root/mode/rep_config /etc/ssh/sshd_config "Protocol 2"                "uncomment"
/root/mode/rep_config /etc/ssh/sshd_config "GSSAPIAuthentication yes"  "comment"
/root/mode/rep_config /etc/ssh/sshd_config "GSSAPIAuthentication no"   "uncomment"
/root/mode/rep_config /etc/ssh/ssh_config  "GSSAPIAuthentication"      "no"

# port 22 -> 3305

cat /etc/ssh/sshd_config | grep "^Port " >/dev/null ||
{
if cat /etc/ssh/sshd_config | grep "^#Port 22" >/dev/null; then
   cat /etc/ssh/sshd_config | sed -re "/^#Port 22.*/ a Port 3305"  > /root/mode/tmp/hhrysshd$$.tmp
   cp -f /root/mode/tmp/hhrysshd$$.tmp /etc/ssh/sshd_config
   rm -f /root/mode/tmp/hhrysshd$$.tmp
else
   echo "Port 3305" >> /etc/ssh/sshd_config
fi
}

#

/etc/init.d/sshd restart >/dev/null 2>&1

#

