#!/bin/bash
# ------------------------------------------------------------------
# function:log mode action
# ------------------------------------------------------------------

{
echo "[exec] $1" 
echo "       at `LANG=en_US;date`"
} >> /root/mode/logs/modelog 

