#!/bin/bash
#-----------------------------------------------------------------------
# function:
#           monitor load process 
# usage   :
#           ./monload <loadprocessid> <IP> <database>
# ----------------------------------------------------------------------

# test process

if ! ps -ef | grep -E "^[^ ]+ +$1 +.*seecfg" >/dev/null; then
   exit 1
fi

#

if echo "$3" | grep -E "^\(" >/dev/null; then
   H3="$3"
else
   H3="($3)"
fi

# local ip addresses 

if [ "$2" = "localhost" ]; then
   Hlip="($2)"
elif [ "$2" = "127.0.0.1" ]; then
   Hlip="($2):[0-9]+"
else
   Hlip="$(/root/mode/getstrips):[0-9]+"
fi

# get status 

Hinsmark="(INSERT INTO|insert  into)"
Hmlfile=/root/mode/tmp/hmonload$$.tmp
/root/mode/seecfg $2 "show processlist" > $Hmlfile
if cat $Hmlfile | grep -Pi  "^(\|[^\|]*){2}\| *$Hlip *\| *$H3 *(\|[^\|]*){3}\| *$Hinsmark \`" > /dev/null; then
    Hletter=$(
    LANG=en_US;
    cat $Hmlfile | 
    grep -Pi "^(\|[^\|]*){2}\| *$Hlip *\| *$H3 *(\|[^\|]*){3}\| *$Hinsmark \`" |
    head -n 1 |
    sed -re "s/^(\|[^\|]*){2}\| *$Hlip *\| *$H3 *(\|[^\|]*){3}\| *$Hinsmark \`(.).*/\6/" |
    tr "A-Z" "a-z")
    echo -n "$Hletter"
fi

#

rm -f $Hmlfile

# end 

