#!/bin/bash
#

[ -f /root/servers.txt ] || exit

#

for i in `cat /root/servers.txt | grep -v "^#" | grep -E "^${1:-.*}$"`; do
   echo $i
   scp -p /mode.tar.gz $i:/
   ssh -q $i "cd /;tar xzvf mode.tar.gz >/dev/null 2>&1"
done
