#!/bin/bash
#

[ -f /root/servers.txt ] || exit

for i in `cat /root/servers.txt | grep -v "^#" | grep -E "^${1:-.*}$"`; do
   echo $i
   scp /root/.ssh/id_rsa.pub $i:/root/chryc$$
   ssh $i "mkdir -p /root/.ssh;chmod 700 /root/.ssh;touch /root/.ssh/authorized_keys;cat /root/.ssh/authorized_keys | grep \"\`cat /root/chryc$$\`\" > /dev/null  || cat /root/chryc$$ >> /root/.ssh/authorized_keys"
   ssh $i "rm -f /root/chryc$$"
done
