#!/bin/bash 
# ------------------------------------------------------------------------------------------------------------------------------------------------------
# function:
#          This script extracts the worst sqls ordered by rows_sent(use only the last 500000 lines)
# usages  :
#          ./sbadsql_rows_sent
# e.g.    :
#          ./sbadsql_rows_sent
# -----------------------------------------------------------------------------------------------------------------------------------------------------

# the MySQL slow.log

Hfile=`ls -1t /var/lib/mysql/*-slow.log 2>/dev/null | head -n 1`
[ -z "$Hfile" ] && exit 

# use the last 500000 lines for analization

Hslowlog=/root/mode/tmp/Hslowlog$$.tmp
tail -n 500000 $Hfile > $Hslowlog

# filter

cat $Hslowlog |
sed -re "/^(# User@Host: )/ i # Time: unknown" | sed -re "s/$/HrYhBy/" |
tr -d "\n" |
sed -re "s/(# Time: [0-9]{6} [0-9]{2}:[0-9]{2}:[0-9]{2}HrYhBy)# Time: unknownHrYhBy/\n\1/g" | sed -re "s/(# Time: ([0-9]{6} |unknown))/\n\1/g" |
grep -E "Rows_sent: [0-9]{4,}" |
grep -E -v "/\*!40001 SQL_NO_CACHE \*/" |
sed -re "s/(.*Rows_sent: ([0-9]+).*)/\2 \1/" |
sort -gr | sed -re "s/^[0-9]+ (.*)/\1/" |
grep -n ""    |
sed -re "1,10 s/^([0-9]+):/# Ranked \1 !!! 元芳，怎么办呢?\n#\n/" |
sed -re "11,$ s/^([0-9]+):/# Ranked \1\n#\n/" |
sed -re "1 i #\n# Mode generated bad sql list,with most rows_sent sqls ranking first$Hfrom\n#" |
sed -re '/Rows_sent: [0-9]{5}([^0-9]|$)/ i # mode comment: bad sql!\n#' |
sed -re '/Rows_sent: [0-9]{6}([^0-9]|$)/ i # mode comment: very bad sql!\n#' |
sed -re '/Rows_sent: [0-9]{7,}/i # mode comment: extra bad sql!\n#' |
sed -re "s/HrYhBy/\n/g"

# rm tmp

rm -f $Hslowlog 

# end 

