#!/bin/bash

Hbinfile=`/root/mode/dumpattr -b "/root/mode/dump/portal_jt.sql"`

if [ -z "$Hbinfile" ]; then
   /root/mode/modemsg Inc_jt "Please check if the dump file exists!" more
fi

/root/mode/dumpattr -i $Hbinfile >/root/mode/dump/Inc_jt.sql
