#!/bin/bash

# edm ...

/root/zhangh/migInc/mdumpzlf

# multiple databases

echo "# mode generated header" > /root/mode/dump/portals.sql
mysqldump -uroot -pdeviskaifa -h10.252.82.87 --opt --single-transaction --master-data=2 -F -R --add-drop-database --databases portal_group portal_member >> /root/mode/dump/portals.sql


