#!/bin/bash

cat "$1" | sed -re "s/$/HrYhBy/" | tr -d "\n" | sed -re  "s/(HrYhBy)( =+ server )/\n\2/g"  | 
sed -re "s/(.*Rows_sent: ([0-9]+).*)/\2 \1/"   | sort -gr |
sed -re "s/^[0-9]+ (.*)/\1/" | 
sed -re "s/HrYhBy/\n/g"  

