#!/bin/bash 

# confirmation

if [ `/root/mode/traceps "crond"` = 'suc' ]; then
   export HBLACKBOX2=1
fi
if /root/mode/confirm "Are you sure to do incremental load" more; then
   # execute the incremental sql
   {
   /root/mode/modemsg execinc "Executing incremental sql ......" more
   date
   export HNoBiNlOg=DaNgEr
   export Hmysql_force=YeS
   /root/mode/seecfg /root/mode/dump/Inc.sql
   date
   } 2>&1 | tee -a /root/mode/logs/execinc.log
fi

# end

