#!/bin/bash 

Hsshmac=`/root/imode/gc_sshc_sshmac "$1"`
if [ -z "$Hsshmac" ]; then
   exit
fi
if ! /root/imode/gc_sshmac_ok "$Hsshmac"; then
   exit
fi
cat /root/imode/.colldata_db1 | eval $Hsshmac

# end


