#!/bin/bash

. /root/mode/mysqldip 

if [ -n "$1" ]; then
   HDBNAME="$1"
else
   HDBNAME=`cat /root/antDep/build.properties 2>/dev/null | tr -d "\r" | grep -E "^db\.name=" | sed -re "s/.*=(.*)/\1/"`
   [ -z "$HDBNAME" ] && exit 1
fi

#

/root/mode/seecfg $HMYSQLDIP \
"select hotel_group_id,(select b.code from hotel_group b where b.id=hotel.hotel_group_id) as hotel_group_code,
        id as hotel_id,code hotel_code,
        descript hotel_descript,
        (select min(c.biz_date) from audit_flag c where c.hotel_group_id=hotel.hotel_group_id and c.hotel_id=hotel.id ) as biz_date,
        (select a.day99 from rep_jie a where a.hotel_group_id=hotel.hotel_group_id and a.hotel_id=hotel.id and
                                             a.classno=(select max(b.classno) from rep_jie b where b.hotel_group_id=a.hotel_group_id and b.hotel_id=a.hotel_id)) as rep_jie,
        (select ifnull(sum(a.sumcre),0) from rep_dai a where a.hotel_group_id=hotel.hotel_group_id and a.hotel_id=hotel.id and a.classno='01010') +
        (select ifnull(sum(a.debit-a.credit),0) from rep_dai a where a.hotel_group_id=hotel.hotel_group_id and a.hotel_id=hotel.id and (a.classno='02000' or a.classno='03000')) as rep_dai

        from hotel
        where (select min(c.biz_date) from audit_flag c where c.hotel_group_id=hotel.hotel_group_id and c.hotel_id=hotel.id) = date(now())
              and 
              (select a.day99 from rep_jie a where a.hotel_group_id=hotel.hotel_group_id and a.hotel_id=hotel.id and 
                                                   a.classno=(select max(b.classno) from rep_jie b where b.hotel_group_id=a.hotel_group_id and b.hotel_id=a.hotel_id))
              <>
             (select ifnull(sum(a.sumcre),0) from rep_dai a where a.hotel_group_id=hotel.hotel_group_id and a.hotel_id=hotel.id and a.classno='01010') +
             (select ifnull(sum(a.debit-a.credit),0) from rep_dai a where a.hotel_group_id=hotel.hotel_group_id and a.hotel_id=hotel.id and (a.classno='02000' or a.classno='03000'))
        order by hotel_group_id,id" $HDBNAME

# end

