#!/bin/bash

# get mysql server ip

. /root/mode/mysqldip

#

/root/mode/seecfg -s $HMYSQLDIP "show processlist" | grep -Pi  "\t([0-9]{4,}|[6789][0-9]{2})\t(Sending data|Copying to tmp table|preparing)\tselect" | grep -iv "40001 SQL_NO_CACHE" |  sed -re "s/^([0-9]+).*/\/root\/mode\/seecfg $HMYSQLDIP 'kill \1'/" | bash

# kill bad sqls by ZLF

/root/mode/seecfg -s $HMYSQLDIP "show full processlist" | grep -Pi  "\t([0-9]{3,})\t(NULL|Sorting result)\tselect.*a\.card_no +like +'%[^ ]+%'" | grep -iv "40001 SQL_NO_CACHE" |  sed -re "s/^([0-9]+).*/\/root\/mode\/seecfg $HMYSQLDIP 'kill \1'/" | bash

# end 


