---
# 检查所有服务器底表情况


- hosts: icheckdb
  remote_user: root
  gather_facts: no

  tasks:
#    - name: download mode
#      get_url: url=http://www.ipms.cn:8090/mode.tar.gz dest=/
#
#    - name: download packages
#      get_url: url=http://www.ipms.cn:8090/packages.tar.gz dest=/

    # copy 在解压文件之前，是否先将文件复制到远程主机，默认为yes。若为no，则要求目标主机上压缩包必须存在
#    - name: tar zxvf mode
#      unarchive: copy=yes src=/mode.tar.gz dest=/

#    - name: tar zxvf packages
#      unarchive: copy=yes src=/packages.tar.gz dest=/
    # 将执行文件从主控机传至远程主机根目录(/)
    - name: hcheck
      copy: src=/root/hcheck dest=/root/
    # 赋予权限
    - name: hcheck auth
      file: path=/root/hcheck recurse=on mode=744 owner=root group=root
    # 执行文件
#    - name: Iseecfg
#      shell: /root/hcheck/Iseecfg /root/hcheck/chksql
    # 删除执行文件
#    - name: rm hcheck
#      file: path=/root/hcheck state=absent