INSERT INTO basecode VALUES (	'function_class',	'00',	'系统功能',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'01',	'基本功能',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'02',	'工作界面',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'03',	'应用模块',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'04',	'BOS 管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'05',	'散客操作',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'06',	'团体操作',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'07',	'会议室管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'08',	'AR应收帐',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'09',	'综合收银',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'10',	'帐务审核',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'11',	'历史档案',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'12',	'前台帐务',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'13',	'消费帐',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'16',	'电话计费',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'21',	'公关销售',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'23',	'房态管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'25',	'客房中心',	'','F',	'F',0,	'');
INSERT INTO basecode VALUES (	'function_class',	'27',	'商务中心',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'31',	'贵 宾 卡',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'33',	'成本分析',	'',	'F',	'F',0,	'');
INSERT INTO basecode VALUES (	'function_class',	'37',	'仓库管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'39',	'VOD 计费',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'41',	'门卡发行',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'43',	'Int 计费',	'',	'F',	'F',0,	'');
INSERT INTO basecode VALUES (	'function_class',	'45',	'经理查询',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'50',	'票据管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'53',	'人事管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'54',	'工资管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'55',	'固定资产',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'56',	'工程设备',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'88',	'PDA应用',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'90',	'资源管理',	'',	'F',	'F',	0,	'');
INSERT INTO basecode VALUES (	'function_class',	'99',	'其    他',	'',	'F',	'F',	0,	'');
