#!/bin/bash
# -----------------------------------------------------------------
# function:
#           clear linux caches 
# e.g.    :
#          ./clrcache       # clear caches according to statistics  
#          ./clrcache 1     # clear caches forcibly
# -----------------------------------------------------------------


# check authority 

if [ "$HOME" != "/root" -a "$HOME" != "/" ]; then
   exit 1
fi

# check linux version  

if [ -x /etc/ifconfig ]; then
   exit 0
fi

# new method to check reentrance 

if /root/zhangh/hshell/withyou $$ clrcache; then
   if [ `/root/zhangh/hshell/traceps "crond"` != 'suc' ]; then
      /root/zhangh/hshell/hmsg clrcache "Another clrcache task is running!" more 
   fi
   # No wait.All clrcache processes may abort almost simultaneously 
   exit 
fi

# collect data 

HTTLMEM=`free  | grep "Mem:" | sed -e "s/^Mem: *\([0-9]\{1,\}\).*/\1/"`
HUSED1=`free   | grep "Mem:" | sed -re "s/^Mem: *([0-9]+) *([0-9]+).*/\2/"`
HUSED2=`free   | grep "buffers/cache:" | sed -re "s/.*buffers\/cache: *([0-9]+).*/\1/"`
HUSED3=`free   | grep "Swap:" | sed -re "s/^Swap: *([0-9]+) *([0-9]+).*/\2/"`
HUSED1PT=`echo "$HUSED1 * 100 / $HTTLMEM" | bc`
HUSED2PT=`echo "$HUSED2 * 100 / $HTTLMEM" | bc`
HUSED3PT=`echo "($HUSED2+$HUSED3) * 100 / $HTTLMEM" | bc`
HUSED4PT=`echo "($HUSED1-$HUSED2) * 100 / $HTTLMEM" | bc`

# check data   

if [ "$1" = "1" ]; then
   :
elif [ $HUSED1PT -ge 88 -o $HUSED3 -gt 0 ]; then
   :
elif ps -ef | grep -E "/(mload|mdump)( |$)" | grep -v grep > /dev/null; then
   :
else
   exit
fi

# 

if [ $HUSED3 -le 0 ]; then
   # ------------------------------
   # swap has not been used 
   # ------------------------------
   if [ $HUSED4PT -ge 5 ]; then
      sync
      echo 3 > /proc/sys/vm/drop_caches
   fi
else
   if [ $HUSED3PT -le 97 ]; then
      # --------------------
      # clrcache first
      # --------------------
      sync
      echo 3 > /proc/sys/vm/drop_caches
      # clear swap
      /sbin/swapoff -a && /sbin/swapon  -a
   elif [ $HUSED3PT -le 99 ]; then
      # -------------------------------------------------------------------------------
      # I don't know if 'swapoff -a' will succeed
      # System administrator should stop some services,then restart them to free memory 
      # -------------------------------------------------------------------------------
      /root/zhangh/hshell/hmsg clrcache "No sufficient memory for the workload!!!" more
   else
      # -------------------------------------------------------------------------------
      # situation:  memory stress
      # suggestion: add system memory
      # -------------------------------------------------------------------------------
      /root/zhangh/hshell/hmsg clrcache "No sufficient memory for the workload!!!"
      /root/zhangh/hshell/hmsg clrcache "Please add system memory as soon as possible!!!" more
   fi
fi

# end of script


