#!/bin/bash
# ---------------------------------------------
# function:
#          test the executability of sql file
# usage   :
#          ./dlsql <dbname> <xxx.sql>
# ---------------------------------------------

#

. /root/zhangh/hshell/mysqldip

#

if /root/zhangh/hshell/isdump "$2"; then
   exit
fi

HDBNAME="$1"
HSQLFILE="$2"
HOBJECTS=`cat "$HSQLFILE" | 
          sed -nre "s/^[ \t]*----each----:// p" | 
          sed -re  "s/%/HrYqHfHbYhSc/g" | 
          sed -re  "s/('\]\]|'\]\[)/%\1/g" | 
          sed -re "s/\[[ \t]*default[ \t]*=('[^%]*%')\]/\[\ndefault=\1\n\]/g" | 
          sed -re "/^default=/ s/ /HrYhSc/g" | 
          tr -d "\r\n\t " | sed -r -e "s/HrYhSc/ /g" | 
          sed -re "s/(\[type=[^]]+)unsigned/\1 unsigned/g" | 
          sed -re "s/(\[type=[^]]+)zerofill/\1 zerofill/g"` 
if [ -n "$HOBJECTS" ]; then
   /root/zhangh/hshell/testobjects $HMYSQLDIP "$HOBJECTS" "$HDBNAME"
fi

#

