#!/bin/bash
# ===============================================
# Function:
#   add Linux user and gen password 
# Date:
#   :2015-05-04
# ===============================================
shopt -s expand_aliases
alias ssh='ssh -q'

if [ -z "$1" ]; then
  /root/zhangh/hshell/hmsg douseradd "Please provide ssh code or ip !!!" more
  exit
fi

if [ -z "$2" ]; then
  /root/zhangh/hshell/hmsg douseradd "Please provide linux user!!!" more
  exit
fi

if [ -z "$3" ]; then
  /root/zhangh/hshell/hmsg douseradd "Please provide linux user password!!!" more
  exit
fi

if echo "$1" | grep "root" > /dev/null; then
  Hcode=`echo "$1" | sed -e "s/root@//"`
fi

echo
echo "=================== Server $Hcode ===================="
echo

ssh $1 "useradd $2;echo $3 | passwd --stdin $2" 
