#!/bin/bash
# ===============================================
# Function:
#      工程检查脚本
#      ./domaint IP hotelcode
# Date:
#     2018.1.30
# ===============================================
#


for HDNAME in `ssh $1 "/root/mode/seecfg -s 'show databases'" | grep "portal" | grep -v "portal_group" | grep -v "portal_member" | grep -v "tr"`; do
    # 不能使用while的原因在于 while read line是一次性将文件信息读入并赋值给变量，while中使用重定向
    # for是每次读取文件中一个以空格为分割符的字符串
    # ssh $1 "/root/mode/seecfg -s \"select hotel_group_id,id from hotel where if('$2' is null,1=1,code like '%$2%') order by id\" $HDNAME" | 
    # while read -r GROUPID HOTELID;do
    #     ssh $1 "/root/mode/seecfg \"CALL up_ihotel_maint_check_base($GROUPID,$HOTELID)\" $HDNAME"
    #     ssh $1 "/root/mode/modemsg domaint \" This is a line !!! \" more"
    #     ssh $1 "/root/mode/seecfg \"CALL up_ihotel_maint_check_balance($GROUPID,$HOTELID)\" $HDNAME"
    # done
    for GROUPID in `ssh $1 "/root/mode/seecfg -s \"select id from hotel_group order by id\" $HDNAME"`; do
        for HOTELID in `ssh $1 "/root/mode/seecfg -s \"select id from hotel where hotel_group_id = $GROUPID and if('$2' is null,1=1,code like '%$2%') order by id\" $HDNAME"`; do
            # echo $GROUPID "<--->" $HOTELID
            ssh $1 "/root/mode/seecfg \"CALL up_ihotel_maint_check_base($GROUPID,$HOTELID)\" $HDNAME"
            ssh $1 "/root/mode/modemsg domaint \" This is a line !!! \" more"
            ssh $1 "/root/mode/seecfg \"CALL up_ihotel_maint_check_balance($GROUPID,$HOTELID)\" $HDNAME"            
        done
    done
done
