#!/bin/bash
# ===============================================
# Function:
#     批量执行生成sql脚本，若中断，取出中断的服务器代码后带入参数继续执行
#     针对如何继续还有一种方法是记录日志，从日志中判断
# Date:
#     2018.1.29
# ===============================================
#


if [ ! -n "$2" ]; then  
  for i in `cat /root/servers.txt | grep -v "^#" | grep -E "^${1:-.*}$"`; do
    IPmsg=`cat /etc/hosts | grep $i`
    echo $IPmsg
    ssh $i "mkdir /root/checksql"
    scp -Cp /root/up_ihotel_maint*.sql $i:/root/checksql

    # 取出需执行的库
    for j in `ssh $i "/root/mode/seecfg -s 'show databases'" | grep "portal" | grep -v "portal_group" | grep -v "portal_member"`; do
      ssh $i "/root/mode/updatedb.sh /root/checksql $j"
  #    ssh $i "/root/mode/seecfg \"SELECT b.id,b.code,b.descript,a.server_ip FROM pos_ip a,hotel b WHERE a.server_ip LIKE '%115.159.112.225%' AND b.hotel_group_id=a.hotel_group_id GROUP BY a.hotel_id\" $j"
    done

    ssh $i "rm -Rf /root/checksql"
  done
else
  for i in `cat /root/servers.txt | grep -E '^[a-zA-Z0-9]' | sed -ne "/^$2/,$ p" | grep -v "^#"`; do
    IPmsg=`cat /etc/hosts | grep $i`
    echo $IPmsg
    ssh $i "mkdir /root/checksql"
    scp -Cp /root/up_ihotel_maint*.sql $i:/root/checksql

    # 取出需执行的库
    for j in `ssh $i "/root/mode/seecfg -s 'show databases'" | grep "portal" | grep -v "portal_group" | grep -v "portal_member"`; do
      ssh $i "/root/mode/updatedb.sh /root/checksql $j"
  #    ssh $i "/root/mode/seecfg \"SELECT b.id,b.code,b.descript,a.server_ip FROM pos_ip a,hotel b WHERE a.server_ip LIKE '%115.159.112.225%' AND b.hotel_group_id=a.hotel_group_id GROUP BY a.hotel_id\" $j"
    done

    ssh $i "rm -Rf /root/checksql"
  done
fi
