#!/bin/bash
# =================================================================
# Function:
#		Show Server Basic Information,such as
#	Hostname CPU RAM IP ...
# =================================================================

touch /root/zhangh/hshell/logs/info$$.tmp

# Server hostname
echo "Linux Hostname: `hostname`" >> /root/zhangh/hshell/logs/info$$.tmp

# Linux_release
echo "Linux Version : `uname -r`" >> /root/zhangh/hshell/logs/info$$.tmp

# Linux issue
if [ -e /etc/issue ]; then
	echo "Linux Issue   : `cat /etc/issue | grep release`" >> /root/zhangh/hshell/logs/info$$.tmp
fi

# CPU
#/root/zhangh/hshell/cpuinfo
Hcpus=`cat /proc/cpuinfo | grep "physical id" | sort -u | wc -l`

if [ $Hcpus -gt 0 ]; then
	Hcores=`cat /proc/cpuinfo | grep "cpu cores" | sort -u | sed -re "s/^[^0-9]+([0-9]+)/\1/"`	
	Hsiblings=`cat /proc/cpuinfo | grep "siblings" | sort -u | sed -re "s/^[^0-9]+([0-9]+)/\1/"`	
	Hht=$[$Hsiblings/$Hcores]
	echo -n "Linux CPU     : ${Hcpus} cpu * ${Hcores} cores" >> /root/zhangh/hshell/logs/info$$.tmp
	if [ $Hht -gt 1 ]; then
		echo -n " * ${Hht} HT" >> /root/zhangh/hshell/logs/info$$.tmp
	fi
	echo " = `cat /proc/cpuinfo | grep processor | wc -l` logcial processor(s)" >> /root/zhangh/hshell/logs/info$$.tmp
else
	echo "Virtual machine: `cat /proc/cpuinfo | grep processor | wc -l` logcial processor(s)" >> /root/zhangh/hshell/logs/info$$.tmp
fi

# IPs
if [ -e /sbin/ifconfig ]; then
	echo "Active IP     :" >> /root/zhangh/hshell/logs/info$$.tmp
	for i in `/sbin/ifconfig | grep "inet addr:.*Bcast" | sed -e "s/ *Bcast.*//" -e "s/.*inet addr://"`; do
		echo "                $i" >> /root/zhangh/hshell/logs/info$$.tmp
	done
fi

# RAM
# free -m | grep "Mem:" | sed -re "s/Mem: *//" | sed -re "s/^([0-9]+).*/\1/"
# free -m | grep "Mem:" | sed -re "s/Mem: *//" | sed -re "s/^([0-9]+) *([0-9]+).*/\2/"
if [ -e /proc/meminfo ];then
	echo "MemTotal      : `cat /proc/meminfo | grep "MemTotal" | sed -re "s/MemTotal: *([0-9]+).*/\1/"`" >> /root/zhangh/hshell/logs/info$$.tmp
	echo "MemFree       : `cat /proc/meminfo | grep "MemFree" | sed -re "s/MemFree: *([0-9]+).*/\1/"`" >> /root/zhangh/hshell/logs/info$$.tmp
	echo "SwapTotal     : `cat /proc/meminfo | grep "SwapTotal" | sed -re "s/SwapTotal: *([0-9]+).*/\1/"`" >> /root/zhangh/hshell/logs/info$$.tmp
	echo "SwapFree      : `cat /proc/meminfo | grep "SwapFree" | sed -re "s/SwapFree: *([0-9]+).*/\1/"`" >> /root/zhangh/hshell/logs/info$$.tmp
fi

# df disk use condition
echo >> /root/zhangh/hshell/logs/info$$.tmp
echo "/      space usage: `df | grep -E "\/$" | sed -re "s/^\/dev\/[a-z]+[0-9]* *([0-9]+) *([0-9]+) *([0-9]+) *([0-9]+)%.*/\4%/"`" >> /root/zhangh/hshell/logs/info$$.tmp
echo "/var   space usage: `df | grep -E "\/var$" | sed -re "s/^\/dev\/[a-z]+[0-9]* *([0-9]+) *([0-9]+) *([0-9]+) *([0-9]+)%.*/\4%/"`" >> /root/zhangh/hshell/logs/info$$.tmp
echo "/DISK2 space usage: `df | grep -E "\/DISK2$" | sed -re "s/^\/dev\/[a-z]+[0-9]* *([0-9]+) *([0-9]+) *([0-9]+) *([0-9]+)%.*/\4%/"`" >> /root/zhangh/hshell/logs/info$$.tmp


cat /root/zhangh/hshell/logs/info$$.tmp

rm -f /root/zhangh/hshell/logs/info$$.tmp
