#!/bin/bash
# =============================================================
# Function:
#			show server CPU condition
# =============================================================

Hcpus=`cat /proc/cpuinfo | grep "physical id" | sort -u | wc -l`

if [ $Hcpus -gt 0 ]; then
	Hcores=`cat /proc/cpuinfo | grep "cpu cores" | sort -u | sed -re "s/^[^0-9]+([0-9]+)/\1/"`	
	Hsiblings=`cat /proc/cpuinfo | grep "siblings" | sort -u | sed -re "s/^[^0-9]+([0-9]+)/\1/"`	
	Hht=$[$Hsiblings/$Hcores]
	echo -n "${Hcpus} cpu * ${Hcores} cores"
	if [ $Hht -gt 1 ]; then
		echo -n " * ${Hht} HT"
	fi
	echo " = `cat /proc/cpuinfo | grep processor | wc -l` logcial processor(s)"
else
	echo "Virtual machine: `cat /proc/cpuinfo | grep processor | wc -l` logcial processor(s)"
fi
