#!/bin/bash
# ===============================================
# Function:
#   Single DB Split fenku 
# Date:
#   2016-03-30
# Such as:
#	/root/zhangh/hshell/splitdb portal_f
# ===============================================

export HBLACKBOX2=1
export HNoBiNlOg=DaNgEr
export Hmysql_force=YeS

# get mysql server ip
. /root/mode/mysqldip

# Default database to dump is portal or portal_f
if [ -z "$1" ]; then
   HDBNAME=portal
   if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show databases like '$HDBNAME'" | grep -i "^$HDBNAME"` ]; then
      HDBNAME=portal_f
      if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show databases like '$HDBNAME'" | grep -i "^$HDBNAME"` ]; then
         echo "Neither Database portal nor database portal_f exists at $HMYSQLDIP2!" && exit 1
      fi
   fi
else
   HDBNAME="$1"
   if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show databases like '$HDBNAME'" | grep -i "^$HDBNAME"` ]; then
       echo "Database $HDBNAME doesn't exist at $HMYSQLDIP2!" && exit 1
   fi
fi

if [ ! -f /root/mode/sdump -o ! -f /root/mode/sload ]; then
  echo "This is no sdump or sload script!!!" && exit 1 
fi

if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show tables from \\\`$HDBNAME\\\` like 'card\_base'"` ]; then
  echo "splitdb Cannot be executed repeatedly in Database $HDBNAME!!!" && exit 1 
fi

# repair hotel.client_type and clean invalid data
/root/mode/seecfg "/root/zhangh/hshell/up_ihotel_zhangh_init_data.sql" $HDBNAME
/root/mode/seecfg "/root/zhangh/hshell/up_ihotel_zhangh_grp_analyse.sql" $HDBNAME

# Empty folder file
rm -Rf /fenku/dumps/

# create dump directory
mkdir -p /fenku
if [ -d /DISK2 ]; then
  if [ ! -L /fenku ]; then
    mv /fenku /DISK2
    ln -s /DISK2/fenku /fenku
  fi
fi

mkdir -p /fenku/dumps

rm -Rf /root/zhangh/hshell/logs/*.log

# create databases group member 
if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show databases like 'portal_group'" | grep -i "portal_group"` ]; then
   /root/mode/seecfg "create database portal_group character set utf8"
fi

if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show databases like 'portal_member'" | grep -i "portal_member"` ]; then
   /root/mode/seecfg "create database portal_member character set utf8"
fi

# sdump all tables and tb_nodata.txt structure
{
  echo
  echo "sdump begin at `LANG=en_US;date`"
  echo

  /root/mode/sdump -S $HDBNAME /fenku/dumps --include-tables `cat /root/zhangh/hshell/tb_nodata.txt`

  /root/mode/sdump -R $HDBNAME /fenku/dumps --exclude-tables `cat /root/zhangh/hshell/tb_nodata.txt`

  echo
  echo "sdump end at `LANG=en_US;date`"
  echo
} 2>&1 | tee -a /root/zhangh/hshell/logs/sdump.log

# check sdump error and stop splitdb process 
if cat /root/zhangh/hshell/logs/sdump.log | grep "SELECT INTO OUTFILE" > /dev/null; then
  /root/zhangh/hshell/hmsg splitdb-sdump "An error occurred in sdump process and please check it ......" && exit 1
fi

if [ ! -f /fenku/dumps/hotel.txt ]; then
  /root/zhangh/hshell/hmsg splitdb-sdump "Mysqldump Error and please MySQL restart ......" && exit 1
fi

# sload tables into group or member database
{ 
  echo
  echo "sload begin at `LANG=en_US;date`"
  echo

  /root/mode/sload -f -S portal_group  /fenku/dumps --include-tables `cat /root/zhangh/hshell/tb_nodata.txt`
  /root/mode/sload -f -S portal_member /fenku/dumps --include-tables `cat /root/zhangh/hshell/tb_nodata.txt`

  /root/mode/sload -f -R portal_group  /fenku/dumps --include-tables `cat /root/zhangh/hshell/tb_same.txt`
  /root/mode/sload -f -R portal_member /fenku/dumps --include-tables `cat /root/zhangh/hshell/tb_same.txt`

  /root/mode/sload -f portal_group     /fenku/dumps --include-tables `cat /root/zhangh/hshell/tb_group.txt`
  /root/mode/sload -f portal_member    /fenku/dumps --include-tables `cat /root/zhangh/hshell/tb_member.txt`

  echo
  echo "sload end at `LANG=en_US;date`"
  echo
} 2>&1 | tee -a /root/zhangh/hshell/logs/sload.log

if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show tables from portal_member like 'card\_base'"` ]; then
  echo "card_base not in Database portal_member and splitdb failed !!!" && exit 1 
fi

Hrows=`/root/mode/seecfg -s $HMYSQLDIP "select count(1) from hotel" portal_group`
if [ $Hrows -eq 0 ]; then
  echo "The table hotel no rows in Group database !!!" && exit 1
fi

# Drop member tables in pms database 
/root/mode/seecfg $HMYSQLDIP "/root/zhangh/hshell/maint_droptb.sql" $HDBNAME
# maint data in pms group member
/root/mode/seecfg $HMYSQLDIP "/root/zhangh/hshell/maint_group.sql" portal_group
