DROP TABLE IF EXISTS `armst`;

CREATE TABLE `armst` (
  `accnt` varchar(200) DEFAULT NULL,
  `name1` varchar(200) DEFAULT NULL,
  `begin_` varchar(200) DEFAULT NULL,
  `end_` varchar(200) DEFAULT NULL,
  `sno` varchar(200) DEFAULT NULL,
  `artype` varchar(200) DEFAULT NULL,
  `balance` varchar(200) DEFAULT NULL,
  `cycle` varchar(200) DEFAULT NULL,
  `phone` varchar(200) DEFAULT NULL,
  `mobile` varchar(200) DEFAULT NULL,
  `fax` varchar(200) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `street` varchar(200) DEFAULT NULL,
  `salesman` varchar(200) DEFAULT NULL,
  `credit` varchar(200) DEFAULT NULL,
  `credit_man` varchar(200) DEFAULT NULL,
  `credit_no` varchar(200) DEFAULT NULL,
  `remark` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `guest`;
CREATE TABLE `guest` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) DEFAULT NULL,
  `sex` varchar(200) DEFAULT NULL,
  `class` varchar(200) DEFAULT NULL,
  `birth` varchar(200) DEFAULT NULL,
  `id_type` varchar(200) DEFAULT NULL,
  `id_des` varchar(200) DEFAULT NULL,
  `id_no` varchar(200) DEFAULT NULL,
  `nation` varchar(200) DEFAULT NULL,
  `address1` varchar(200) DEFAULT NULL,
  `address2` varchar(200) DEFAULT NULL,
  `city` varchar(200) DEFAULT NULL,
  `mobile` varchar(200) DEFAULT NULL,
  `phone` varchar(200) DEFAULT NULL,
  `fax` varchar(200) DEFAULT NULL,
  `interest` varchar(200) DEFAULT NULL,
  `specials` varchar(200) DEFAULT NULL,
  `amenity` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1749 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `membercard`;
CREATE TABLE `membercard` (
  `hotel_group_id` bigint(16) DEFAULT NULL COMMENT '请对照：hotel_group.id。集团编号，',
  `hotel_id` bigint(16) DEFAULT NULL COMMENT '请对照：hotel.id。酒店编号',
  `iss_hotel` varchar(20) DEFAULT NULL COMMENT '请对照：hotel.code。发卡酒店代码',
  `biz_date` datetime DEFAULT NULL COMMENT '导入的积分、储值数据的营业日期',
  `card_id_temp` bigint(16) NOT NULL AUTO_INCREMENT COMMENT '中间数据，不填',
  `member_id_temp` bigint(20) DEFAULT NULL COMMENT '中间数据，不填',
  `account_master_id` bigint(16) DEFAULT NULL COMMENT '中间数据，不填',
  `card_id` bigint(16) DEFAULT NULL COMMENT '中间数据，不填',
  `member_id` bigint(16) DEFAULT NULL COMMENT '中间数据，不填',
  `guest_id` bigint(20) DEFAULT NULL COMMENT '若有导好的客史档案，根据hno填写该值',
  `company_id` bigint(20) DEFAULT NULL COMMENT '若有导好的公司档案，新账号填入',
  `cno` bigint(20) DEFAULT NULL COMMENT '公司档案',
  `card_no` varchar(20) NOT NULL COMMENT '填西软系统中的card_no',
  `card_no2` varchar(20) NOT NULL DEFAULT '' COMMENT '填西软系统中的no,即西软内部卡号',
  `sta` char(2) NOT NULL DEFAULT 'R' COMMENT '状态=R=初始 I-有效,X-销卡,L-挂失,M-损坏,O-停用 S=休眠',
  `card_type` varchar(30) NOT NULL COMMENT '请对照，card_type.code',
  `card_level` varchar(30) NOT NULL COMMENT '请对照，card_level.code',
  `card_src` varchar(30) NOT NULL COMMENT '请对照，code_base.parent_code = ''card_src''',
  `card_name` varchar(50) NOT NULL DEFAULT '' COMMENT '卡上姓名，可以用guest姓名',
  `src` varchar(50) NOT NULL DEFAULT '' COMMENT 'src',
  `src_des` varchar(50) NOT NULL DEFAULT '' COMMENT 'src',
  `mkt` varchar(50) NOT NULL DEFAULT '' COMMENT 'market',
  `ratecode` varchar(20) NOT NULL DEFAULT '' COMMENT '请对照：code_ratecode房价码',
  `posmode` varchar(20) DEFAULT '' COMMENT '请对照：code_base.parent_code = ''pos_mode''餐娱码',
  `date_begin` datetime NOT NULL COMMENT '卡片有效期起',
  `date_end` datetime NOT NULL COMMENT '卡片有效期止',
  `password` varchar(20) NOT NULL DEFAULT '' COMMENT '卡消费密码',
  `salesman` varchar(10) DEFAULT NULL COMMENT '请对照：sales_man.code',
  `crc` varchar(20) DEFAULT NULL COMMENT '写卡效验码',
  `remark` varchar(512) DEFAULT NULL COMMENT '卡上备注',
  `point_pay` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '积分产生余额',
  `point_charge` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '积分消耗余额',
  `point_last_num` int(11) NOT NULL DEFAULT '0' COMMENT '积分记录数，只导余额时填0',
  `card_master` varchar(30) DEFAULT NULL COMMENT '原西软账务系统中，存在多卡公用一账号时，主卡填null，附卡填主卡的card_id_temp',
  `araccnt` varchar(20) DEFAULT NULL COMMENT '原系统账务账号，如AR账号',
  `pay` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '充值金额',
  `charge` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '消费金额',
  `accredit` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '信用金额',
  `last_num` int(11) NOT NULL DEFAULT '0' COMMENT '储值账务记录数，只导余额时填0',
  `freeze` decimal(10,2) DEFAULT '0.00' COMMENT '储值账务冻结金额',
  `pay_code` varchar(10) DEFAULT '' COMMENT '产生期初数据时的付款码',
  `create_user` varchar(20) NOT NULL COMMENT '建卡工号',
  `create_datetime` datetime NOT NULL COMMENT '建卡时间',
  `modify_user` varchar(20) NOT NULL COMMENT '最后修改工号',
  `modify_datetime` datetime NOT NULL COMMENT '最后修改日期',
  `hno` varchar(20) DEFAULT NULL COMMENT '原系统档案号',
  `hname` varchar(60) DEFAULT '' COMMENT '姓名',
  `hlname` varchar(40) DEFAULT '' COMMENT '姓',
  `hfname` varchar(40) DEFAULT '' COMMENT '名',
  `hname2` varchar(100) DEFAULT '' COMMENT '姓名拼音',
  `hname3` varchar(100) DEFAULT '' COMMENT '英文名',
  `hname_combine` varchar(200) DEFAULT '' COMMENT '姓名组合，',
  `sex` varchar(10) DEFAULT '?' COMMENT '请对照：code_base.parent_code = ''card_src'',性别',
  `language` varchar(10) NOT NULL DEFAULT '' COMMENT '请对照：code_base.parent_code = ''language'',语言',
  `birth` datetime DEFAULT NULL COMMENT '生日',
  `nation` varchar(10) NOT NULL DEFAULT '' COMMENT '请对照：code_country.code。国籍',
  `id_code` varchar(10) NOT NULL DEFAULT '?' COMMENT '请对照code_base.parent_code = ''idcode''.证件类型',
  `id_no` varchar(50) NOT NULL DEFAULT '?' COMMENT '证件号码',
  `hremark` text COMMENT '档案备注',
  `hcreate_user` varchar(20) DEFAULT NULL COMMENT '档案创建人',
  `hcreate_datetime` datetime DEFAULT NULL COMMENT '档案创建日期',
  `hmodify_user` varchar(20) DEFAULT NULL COMMENT '档案最后修改人',
  `hmodify_datetime` datetime DEFAULT NULL COMMENT '档案最后修改日期',
  `mobile` varchar(160) DEFAULT NULL COMMENT '手机',
  `phone` varchar(160) DEFAULT NULL COMMENT '电话',
  `email` varchar(160) DEFAULT NULL COMMENT '电邮',
  `country` varchar(10) DEFAULT NULL COMMENT '请对照：code_country.code。住址：国家',
  `state` varchar(40) DEFAULT NULL COMMENT '请对照：code_province.code。住址：省',
  `city` varchar(40) DEFAULT NULL COMMENT '请对照：code_city.code。住址：市',
  `division` varchar(6) DEFAULT NULL COMMENT '请对照：code_city.division。住址：地区',
  `street` varchar(512) DEFAULT NULL COMMENT '住址：地址',
  `zipcode` varchar(12) DEFAULT NULL COMMENT '住址：邮编',
  `loginPW` varchar(20) DEFAULT NULL COMMENT '网站登录密码',
  PRIMARY KEY (`card_id_temp`),
  UNIQUE KEY `Index_1` (`card_no`),
  KEY `Index_3` (`card_no2`),
  KEY `card_id_temp` (`card_id_temp`),
  KEY `member_id_temp` (`member_id_temp`),
  KEY `guest_id` (`guest_id`),
  KEY `ratecode` (`ratecode`),
  KEY `posmode` (`posmode`),
  KEY `hno` (`hno`),
  KEY `cno` (`cno`),
  KEY `card_id` (`card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `up_map_accnt`;
CREATE TABLE `up_map_accnt` (
  `hotel_group_id` int(11) NOT NULL,
  `hotel_id` int(11) NOT NULL,
  `id` bigint(16) NOT NULL AUTO_INCREMENT,
  `accnt_type` varchar(16) NOT NULL COMMENT '比如:登记单=master ',
  `accnt_class` varchar(8) NOT NULL DEFAULT '' COMMENT '比如档案的 F G C A S ',
  `accnt_old` varchar(16) NOT NULL,
  `accnt_new` bigint(16) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Index_1` (`hotel_group_id`,`hotel_id`,`accnt_type`,`accnt_old`),
  KEY `Index_2` (`hotel_group_id`,`hotel_id`,`accnt_type`,`accnt_new`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='所有帐号映射表';

DROP TABLE IF EXISTS `vipcard`;
CREATE TABLE `vipcard` (
  `kno` varchar(200) DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL,
  `sno` varchar(200) DEFAULT NULL,
  `card_type` varchar(200) DEFAULT NULL,
  `begin_` varchar(200) DEFAULT NULL,
  `end_` varchar(200) DEFAULT NULL,
  `mobile` varchar(200) DEFAULT NULL,
  `balance` varchar(200) DEFAULT NULL,
  `crezi` varchar(200) DEFAULT NULL,
  `charge` varchar(200) DEFAULT NULL,
  `charge1` varchar(200) DEFAULT NULL,
  `point` varchar(200) DEFAULT NULL,
  `times` varchar(200) DEFAULT NULL,
  `sta` varchar(200) DEFAULT NULL,
  `idno` varchar(200) DEFAULT NULL,
  `no` varchar(200) DEFAULT NULL,
  `salesman` varchar(200) DEFAULT NULL,
  `cardid` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
