#!/bin/bash

[ -z "$1" ] && exit 1

# check file existence

if [ ! -f "$1" ]; then
   /root/mode/modemsg cdrop "File $1 doesn't exists!" 
   exit 1
fi

#

rm -f /autodrop/* 

#

cat $1 | 
while read i; do
   if [ -z "$i" ]; then
      continue
   fi
   i=`echo $i | tr "A-Z" "a-z" | sed -re "s/ //g"`
cat > /autodrop/$i.sql << EOF
/*
----each----:[$i]
*/
drop table $i;
EOF
   

done

