#!/bin/bash

# slow.log

if [ -n "$1" ]; then
   Hfile="$1"
else
   Hfile=""
fi
if [ -n "$2" ]; then
   Hfrom="(from $2)"
fi

# filter 

cat $Hfile |
sed -re "s/$/HrYhBy/" | 
tr -d "\n" | 
sed -re "s/(#+ [0-9]+)/\n\1/g" |  
grep -E "rtt min" |  
sed -re "s/(.*\/([0-9\.]+)(\/[0-9\.]+){2}.*)/\2 \1/" | 
sort -gr | sed -re "s/^[0-9\.]+ (.*)/\1/" | 
sed -re "s/HrYhBy/\n/g"  

