#!/bin/bash

# slow.log

Hfile="/var/lib/mysql/*.log"
if [ -n "$1" ]; then
   Hfile="$1"
fi
if [ -n "$2" ]; then
   Hfrom="(from $2)"
fi

# filter 

cat $Hfile |
sed -re "/^(# User@Host: )/ i # Time: unknown" |
sed -re "s/$/HrYhBy/" | 
tr -d "\n" | 
sed -r -e "s/(# Time: [0-9]{6} [0-9]{2}:[0-9]{2}:[0-9]{2}HrYhBy)# Time: unknownHrYhBy/\n\1/g" | 
sed -r -e "s/(# Time: ([0-9]{6} |unknown))/\n\1/g" | 
grep -E "Rows_examined: [0-9]{5,}" |
grep -E -v "/\*!40001 SQL_NO_CACHE \*/" | 
sed -re "s/(.*Rows_examined: ([0-9]+).*)/\2 \1/" | 
sort -gr | sed -re "s/^[0-9]+ (.*)/\1/" | 
grep -n "" |
sed -re "1,10 s/^([0-9]+):/# Ranked \1 !!! 元芳，怎么办呢?\n#\n/" |  
sed -re "11,$ s/^([0-9]+):/# Ranked \1\n#\n/" |  
sed -re "1 i #\n# Mode generated bad sql list,with most rows_examined sqls ranking first$Hfrom\n#" | 
sed -re '/Rows_examined: [0-9]{6}([^0-9]|$)/ i # mode comment: bad sql!\n#' |
sed -re '/Rows_examined: [0-9]{7}([^0-9]|$)/ i # mode comment: very bad sql!\n#' |
sed -re '/Rows_examined: [0-9]{8,}/i # mode comment: extra bad sql!\n#' | 
sed -re "s/HrYhBy/\n/g"  

