#!/bin/bash 

#

if echo "$1" | grep -E "(\(|\*|\+|\||\{|\[)" >/dev/null; then 
   Hpat="regexp '^$1$'"
else
   Hpat="like '$1%'"
fi

#

Hlines=`/root/mode/seecfg -s "select code from gc_sshto_servers where code $Hpat order by code" gc_admin`
for i in `echo $Hlines`; do
   Hsc=`/root/imode/gc_sshc_sc "$i"`
   j="$i"
   Hsshmac=`/root/imode/gc_sshc_sshmac "$j"`
   if [ -z "$Hsshmac" ]; then
      continue
   fi
   if ! /root/imode/gc_sshmac_ok "$Hsshmac"; then
      continue
   fi
   #
   Hssh_des=`/root/mode/seecfg -s "select descript from gc_sshto_servers where code='$i'" gc_admin`
   Hssh_ip0=`/root/mode/seecfg -s "select ip0 from gc_sshto_servers where code='$i'" gc_admin`
   Hssh_ip2=`/root/mode/seecfg -s "select ip2 from gc_sshto_servers where code='$i'" gc_admin`
   if [ -z "$Hssh_ip2" ]; then
      Hssh_ip=$Hssh_ip0
   else
      Hssh_ip="$Hssh_ip2 -> $Hssh_ip0"
   fi
   #
   echo 
   # echo "===== [ sshc ]: $j [ sc ]: $Hsc [ ip ]: $Hssh_ip =====" >&2
   Hdbs=`cat /root/imode/.colldata_db | eval $Hsshmac`
   if [ -z "$Hdbs" ]; then
      continue
   fi
   Hdbs=`echo "$Hdbs" | sort | uniq`
   for i1 in `echo $Hdbs`;do
       Hip=`echo $i1 | sed -re "s/(.*):(.*)/\1/"`
       Hdb=`echo $i1 | sed -re "s/(.*):(.*)/\2/"`
       # echo '-----' Hip Hdb $Hip $Hdb
       echo "/root/mode/seecfg $Hip \"select '$Hssh_des' as descript,'$Hssh_ip' as ip,count(distinct a.hotel_group_id,a.hotel_id) as htlcnt,count(a.hotel_group_id) as room_count
                                        from room_no a,audit_flag b  where a.hotel_group_id=b.hotel_group_id and a.hotel_id=b.hotel_id and b.biz_date=date(now())\" $Hdb" | eval $Hsshmac
   done
done

#


