#!/bin/bash 

cat /qcache | grep -B 5 -E "^perc2:[0-9]+" | grep -v "^--" | 
sed -re "s/$/HrYhSc/" | tr -d '\n' |
sed -re "s/(perc2:[0-9\.]+HrYhSc)/\1\n/g" | 
sed -re "/perc2:0HrY/ d" |
sed -re "s/(.*perc2:([0-9\.]+).*)/\2 \1/" | sort -g |
sed -re "s/^([^ ]+ )//" | 
grep -n ""    |
sed -re "s/^([0-9]+):/# Ranked \1\n#\n/" |
sed -re "1 i #\n# Mode generated qcache hit list,with least hit rates ranking first\n#" |
sed -re "s/HrYhSc/\n/g"
