#!/bin/bash
. /root/imode/cfg/.imode_aliases
# -----------------------------------------------

# dbname 

HDBNAME="$1"
if [ -z "$HDBNAME" ]; then
   HDBNAME=portal
fi

#

Hsvdumpdir=`/root/imode/dumpdir`
cd /
mkdir -p /$Hsvdumpdir
for i in `cat /root/getdump.txt | grep -v "^#" | grep -E "^${2:-.*}$"`; do
   echo
   echo "$i"
   echo
   echo "1.execute remote mdump"
   ssh $i "/root/mode/mdump $HDBNAME"
   if ! cat /root/getdump1.txt | grep -E "^$i$" >/dev/null; then
      continue
   fi
   HTARNAME=$HDBNAME-`date +%Y-%m-%d`
   HPNO=$$
   HTMPTAR=/root/mode/tmp/${HTARNAME}-$HPNO.tar.gz
   echo
   echo "2.execute remote tar czvf"
   ssh $i "cd /root/mode/dump;tar czvf $HTMPTAR \`ls -1 $HDBNAME-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9][0-9].sql | sed -n '$ p'\`"
   mkdir -p /$Hsvdumpdir/$i
   echo
   echo "3.get remote tar file $HTMPTAR and put it into /$Hsvdumpdir/$i directory"
   # first scp to local tmp file
   scp $i:$HTMPTAR $HTMPTAR
   # then move to /$Hsvdumpdir/$i/$HTARNAME.tar.gz
   mv -f /root/mode/tmp/${HTARNAME}-$HPNO.tar.gz /$Hsvdumpdir/$i/$HTARNAME.tar.gz
   echo
   echo "4.remove remote tar file $HTMPTAR"
   ssh $i "rm -f $HTMPTAR"
   echo "5.clear caches"
   ssh $i "/root/mode/clrcache 1"
done
