#!/bin/bash 

if [ -n "$1" ];then
   /root/mode/seecfg "SELECT b.code,b.descript,a.server_code,a.app_at,a.apps,a.version,a.deploy_datetime,a.dbip,a.dbname
                      FROM gc_servers_info a,
                           gc_sshto_servers b
                      WHERE a.server_code=b.server_code and 
                            a.apps REGEXP '$1'
                      order by b.code,a.server_code,a.apps" gc_admin
fi
