#!/bin/bash 


#

/root/mode/modepv setdpstat $$ "/bin/bash .*/setdpstat"

Holdsta=`cat /etc/modetsk/dp/dpstatus 2>/dev/null`
if [ -z "$Holdsta" ]; then
   Holdsta=init
fi
if [ -z "$1" ]; then
   echo $Holdsta
else
   if [ "$1" = "send-completed" ]; then
      if echo "$Holdsta" | grep -E "^(init|deploy-completed|send-completed)$" >/dev/null; then
         echo "$1" > /etc/modetsk/dp/dpstatus
         echo "$1"
         exit 0
      else
         echo $Holdsta
         exit 1
      fi
   elif [ "$1" = "send-all-completed" ]; then
      if echo "$Holdsta" | grep -E "^(send-completed)$" >/dev/null; then
         echo "$1" > /etc/modetsk/dp/dpstatus
         echo "$1"
         exit 0
      else
         echo $Holdsta
         exit 1
      fi
   elif [ "$1" = "downloading" ]; then
      if echo "$Holdsta" | grep -E "^(send-all-completed)$" >/dev/null; then
         echo "$1" > /etc/modetsk/dp/dpstatus
         echo "$1"
         exit 0
      else
         echo $Holdsta
         exit 1
      fi
   elif [ "$1" = "download-completed" ]; then
      if echo "$Holdsta" | grep -E "^(downloading)$" >/dev/null; then
         echo "$1" > /etc/modetsk/dp/dpstatus
         echo "$1"
         exit 0
      else
         echo $Holdsta
         exit 1
      fi
   elif [ "$1" = "deploying" ]; then
      if echo "$Holdsta" | grep -E "^(download-completed)$" >/dev/null; then
         echo "$1" > /etc/modetsk/dp/dpstatus
         echo "$1"
         exit 0
      else
         echo $Holdsta
         exit 1
      fi
   elif [ "$1" = "deploy-completed" ]; then
      if echo "$Holdsta" | grep -E "^(deploying)$" >/dev/null; then
         echo "$1" > /etc/modetsk/dp/dpstatus
         echo "$1"
         exit 0
      else
         echo $Holdsta
         exit 1
      fi
   fi
fi


