#!/bin/bash 

if [ "$1" = 't' ]; then
   Hcores=`/root/mode/cpucores`
   Hcores=$[$Hcores/2]
   if [ $Hcores -eq 0 ]; then
      Hcores=1
   fi
   Hdev=`df | grep -E "^/dev/.*" | tail -n 1 | sed -re "s/^([^ ]+).*/\1/"`
   for i in `seq 1 $Hcores`;do
      md5sum $Hdev &
   done
elif [ "$1" = 'k' ]; then
   kill -9 `ps -ef | grep md5sum | grep -v grep  | sed -re 's/^root[^0-9]+([0-9]+).*/\1/'`
fi


