#!/bin/bash
# -----------------------------------------------------
# function:
#           add or adjust certain items of /etc/my.cnf
#
# -----------------------------------------------------

# exclusive execution with wait mode

/root/mode/modepv adjcnf $$ " /bin/bash .*/adjcnf"

[ -f /etc/my.cnf ] || exit 

# binlog etc.

/root/mode/mod_config "/etc/my.cnf" "binlog_format=mixed"               "log-bin"
/root/mode/mod_config "/etc/my.cnf" "binlog_cache_size=16M"             "binlog_format"
/root/mode/mod_config "/etc/my.cnf" "log_bin_trust_function_creators=1" "binlog_cache_size"

# innodb_rollback_on_timeout

/root/mode/mod_config "/etc/my.cnf" "innodb_rollback_on_timeout=1" "innodb_lock_wait_timeout"
/root/mode/mod_config "/etc/my.cnf" "innodb_autoinc_lock_mode=2"   "innodb_rollback_on_timeout"
/root/mode/mod_config "/etc/my.cnf" "wait_timeout=600"             "innodb_autoinc_lock_mode"
/root/mode/mod_config "/etc/my.cnf" "max_connect_errors=999999999" "[mysqld]"
/root/mode/mod_config "/etc/my.cnf" "back_log=4096"                "[mysqld]"

# innodb_flush_log_at_trx_commit

/root/mode/mod_config "/etc/my.cnf" "innodb_flush_log_at_trx_commit=2"

# max_connections

/root/mode/mod_config "/etc/my.cnf" "max_connections=400" "thread_concurrency"
Hgetmc=`/root/mode/mod_config /etc/my.cnf "max_connections" "#Get#"`
Hgetmc=`echo $Hgetmc | sed -re "s/^(0+)(.*)/\2/"`
if echo "$Hgetmc" | grep -E "^[0-9]+$" >/dev/null; then
   Hgetmc=$[$Hgetmc*9/10]
   if [ $Hgetmc -lt 0 ]; then
      Hgetmc=1
   fi
   /root/mode/mod_config "/etc/my.cnf" "max_user_connections=$Hgetmc" "max_connections"
fi

# thread_cache_size

/root/mode/mod_config "/etc/my.cnf" "thread_cache_size=401" "read_rnd_buffer_size"

# [mysqld_safe]

/root/mode/mod_config "/etc/my.cnf" "[mysqld_safe]" "interactive-timeout"
/root/mode/mod_config "/etc/my.cnf" "open-files-limit=20000" "[mysqld_safe]"

# make sure they are there 

/root/mode/mod_config "/etc/my.cnf" "character-set-server=utf8"       "[mysqld]"
/root/mode/mod_config "/etc/my.cnf" "default-storage-engine=INNODB"   "[mysqld]"
/root/mode/mod_config "/etc/my.cnf" "symbolic-links=0"                "default-storage-engine"

# table_open_cache etc.  -- 2012-08-07 --

/root/mode/mod_config "/etc/my.cnf" "table_open_cache=8192"        "max_allowed_packet"
/root/mode/mod_config "/etc/my.cnf" "tmp_table_size=64M"           "table_open_cache"  
/root/mode/mod_config "/etc/my.cnf" "max_heap_table_size=64M"      "table_open_cache"  
/root/mode/mod_config "/etc/my.cnf" "table_definition_cache=2048"  "table_open_cache"

# datadir  -- 2012-08-28 --

/root/mode/mod_config "/etc/my.cnf" "datadir=/var/lib/mysql" "server-id"

# tune_mysql is used to tune this parm dynamically 

/root/mode/mod_config "/etc/my.cnf" "thread_concurrency=8"

# log unefficient queries 

/root/mode/mod_config "/etc/my.cnf" "long_query_time=3"               "default-storage-engine" 
/root/mode/mod_config "/etc/my.cnf" "log-queries-not-using-indexes"   "default-storage-engine"
/root/mode/mod_config "/etc/my.cnf" "slow-query-log"                  "default-storage-engine"
/root/mode/rep_config "/etc/my.cnf" "log-slow-queries"                "comment"

# ---------------------------------------------------------------------------------------------
# key_buffer_size 
# ---------------------------------------------------------------------------------------------
# Default key_buffer_size is adjusted to 64M because of bad sqls using tmp disk tables
#                                                                              -- 2015-08-10 --
# ---------------------------------------------------------------------------------------------

/root/mode/mod_config "/etc/my.cnf" "key_buffer_size=64M"

# ---------------------------------------------------------------------------------------------
# bulk_insert_buffer_size for MYISAM 
# ---------------------------------------------------------------------------------------------
# Set it to a larger value temporarily when using MYISAM tables for fast migration
# ---------------------------------------------------------------------------------------------

/root/mode/mod_config "/etc/my.cnf" "bulk_insert_buffer_size=8M" "key_buffer_size"

# buffers for innodb tables(per thread basic)

/root/mode/mod_config "/etc/my.cnf" "read_buffer_size=3M"
/root/mode/mod_config "/etc/my.cnf" "sort_buffer_size=16M"
/root/mode/mod_config "/etc/my.cnf" "read_rnd_buffer_size=16M"
/root/mode/mod_config "/etc/my.cnf" "join_buffer_size=1M"       "read_rnd_buffer_size"

# 

/root/mode/mod_config "/etc/my.cnf" "innodb_log_buffer_size=16M"

#

/root/mode/rep_config "/etc/my.cnf" "default-character-set=utf8" "comment"

# use innodb plugin for MySQL server version 5.1.57

if rpm -qa | grep -E '^MySQL-server-community-5\.1\.57' >/dev/null || [ -n "$Huse_mycnf_ext" ]; then
   if ! cat /etc/my.cnf | grep -E '^ignore_builtin_innodb' >/dev/null; then 
      Hmyrand=blackboxhry$RANDOM
      cat /etc/my.cnf | sed -re "/^datadir=/ i $Hmyrand" | sed -re "/$Hmyrand/ r /root/mode/impfile/mysql/my.cnf.ext" | sed -re "/$Hmyrand/ d" > /root/mode/tmp/Hmy.cnf.ext$$.tmp
      cp -f /root/mode/tmp/Hmy.cnf.ext$$.tmp /etc/my.cnf
      rm -f /root/mode/tmp/Hmy.cnf.ext$$.tmp
   fi
else
   if cat /etc/my.cnf | grep -E "^(ignore_builtin_innodb|plugin-load=)" >/dev/null; then
      cat /etc/my.cnf | grep -Ev "^(ignore_builtin_innodb|plugin-load=)" > /root/mode/tmp/Hmy.cnf.ext$$.tmp
      cp -f /root/mode/tmp/Hmy.cnf.ext$$.tmp /etc/my.cnf
      rm -f /root/mode/tmp/Hmy.cnf.ext$$.tmp
   fi
fi

# -----------------------------------------------------------------------------------------------
# gc standard template:
#             innodb_file_per_table=0
#             innodb_file_format=barracuda
# -----------------------------------------------------------------------------------------------
# To create a new table with (barracuda - Antelope) row_format,three conditions must be satisfied
#             1.innodb_file_per_table=1
#             2.innodb_file_format=barracuda
#             3.designate table option row_format=compressed(or row_format=dynamic)
# -----------------------------------------------------------------------------------------------

if  [ "`cat /etc/.modesid 2>/dev/null`" != "534787cb-00bb-40d9-8fa6-bf23953993c7" ]; then
   if ! cat /etc/my.cnf | grep -E '^innodb_file_format=' >/dev/null; then
      # set innodb_file_format to barracuda 
      /root/mode/mod_config "/etc/my.cnf"  "innodb_file_format=Barracuda"     "datadir="
   fi
   if ! cat /etc/my.cnf | grep -E '^innodb_file_per_table=' >/dev/null; then
      # set innodb_file_per_table to 0 
      /root/mode/mod_config "/etc/my.cnf"  "innodb_file_per_table=0"     "datadir="
   fi
fi

# secure-file-priv

if rpm -qa | grep -E '^MySQL-server-(5\.[56])' >/dev/null || [ -n "$Huse_secure_file_priv" ]; then
   if /root/mode/mod_config "/etc/my.cnf"  "secure-file-priv="   "log-queries-not-using-indexes" 2>&1 | grep -E "Multiple occurences" >/dev/null; then
      /root/mode/rep_config "/etc/my.cnf"  "secure-file-priv=.*"   "comment"
      /root/mode/rep_config "/etc/my.cnf"  "secure-file-priv="     "D-commented"
      /root/mode/mod_config "/etc/my.cnf"  "secure-file-priv="     "log-queries-not-using-indexes"
   fi
else
   /root/mode/rep_config "/etc/my.cnf"  "secure-file-priv=.*"   "comment"
   /root/mode/rep_config "/etc/my.cnf"  "secure-file-priv="     "D-commented"
fi

# binlog_checksum

if rpm -qa | grep -E '^MySQL-server-(5\.[6])' >/dev/null || [ -n "$Hdisable_binlog_checksum_in_56" ]; then
   /root/mode/mod_config "/etc/my.cnf"  "binlog_checksum=NONE"   "binlog_format="
else
   sed -ci -re "/^binlog_checksum/ d" "/etc/my.cnf"
fi

# end

