#!/bin/bash 

#

if [ "$1" = "fix" ]; then
   Hmode=fix
fi

#

Hcheckdate=`LANG=en_US;date`
cd /usr/local
for i in `ls -d tomcat*/ 2>/dev/null | sed -re "s/\/$//"`;do
    /root/mode/check_tomcat $i || continue
    Hact_stat=`/root/mode/setwsta $i`
    Htom_stat=`/root/mode/tctomcat $i 2>/dev/null`
    if [ -n "$Hact_stat" ]; then
       if [ "$Hact_stat" = "ACT" -a "$Htom_stat" = "down" ]; then
          # tomcat suicide or tomcat was killed 
          echo "Warning: $i $Hact_stat $Htom_stat"
          if [ "$Hmode" = "fix" ]; then
             echo "Execute: /root/mode/start_tomcat $i"
             /root/mode/start_tomcat $i
          fi
       fi
    elif ! /root/mode/isctom $i; then
       if [ "$Htom_stat" = "down" ]; then
          if cat /root/mode/logs/modelog 2>/dev/null | grep -E " $i$" >/dev/null; then
             if ! cat /root/mode/logs/modelog 2>/dev/null | grep -E " $i$" | tail -n 1 | grep -E "/stop_tomcat +$i$" >/dev/null; then
                echo "Warning: $i $Htom_stat"
                if [ "$Hmode" = "fix" ]; then
                   echo "Execute: /root/mode/start_tomcat $i"
                   /root/mode/start_tomcat $i
                fi
             fi
          fi
       fi
    fi
done 2>&1 | 
{
   cat - | tee /root/mode/tmp/Hapc_tom$$.tmp
   if [ -n "`cat /root/mode/tmp/Hapc_tom$$.tmp`" ]; then
      {
         echo 
         echo 
         echo "##################### apc_tom $Hmode #####################"
         echo 
         echo "Checking apache and tomcat consistency at $Hcheckdate"
         echo
         cat /root/mode/tmp/Hapc_tom$$.tmp
      } >> /root/mode/logs/apc_tom.log
   fi
   rm -f /root/mode/tmp/Hapc_tom$$.tmp
}

#

