#!/bin/bash 

#

if [ "$1" = "fix" ]; then
   Hmode=fix
fi

#

Hcheckdate=`LANG=en_US;date`
cd /usr/local
for i in `ls -d tomcat*/ 2>/dev/null | sed -re "s/\/$//"`;do
    /root/mode/check_tomcat $i || continue
    Htom_stat=`/root/mode/tctomcat $i 2>/dev/null`
    if [ "$Htom_stat" != "down" ]; then
       continue
    fi
    if ! cat /root/mode/logs/modelog 2>/dev/null | grep -E " $i$" >/dev/null; then
       continue
    fi
    #
    if ! /root/mode/isctom $i; then
       #
       if cat /root/mode/logs/modelog 2>/dev/null | grep -E " $i$" | tail -n 1 | grep -E "/stop_tomcat +$i$" >/dev/null; then
          continue
       fi
       #
       echo "Warning: $i $Htom_stat"
       if [ "$Hmode" = "fix" ]; then
          echo "Execute: /root/mode/start_tomcat $i"
          /root/mode/start_tomcat $i
       fi
    else
       Hact_stat=`/root/mode/setwsta $i`
       if [ "$Hact_stat" = "ACT" ]; then
          echo "Warning: $i $Hact_stat $Htom_stat"
          if [ "$Hmode" = "fix" ]; then
             if cat /root/mode/logs/modelog 2>/dev/null | grep -E " $i$" | tail -n 1 | grep -E "/stop_tomcat +$i$" >/dev/null; then
                # apache is started with no fixat while tomcat is normallly down
                /root/mode/setwsta $i 2 >/dev/null 2>&1
                echo "Execute: /root/mode/setwsta $i 2"
             else
                # tomcat suicide or tomcat was killed when apache is on
                /root/mode/setwsta $i 2 >/dev/null 2>&1
                sleep 2
                #
                echo "Execute: /root/mode/start_tomcat $i"
                /root/mode/start_tomcat $i
             fi
          fi
       fi
    fi
done 2>&1 | 
{
   cat - | tee /root/mode/tmp/Hapc_tom$$.tmp
   if [ -n "`cat /root/mode/tmp/Hapc_tom$$.tmp`" ]; then
      {
         echo 
         echo 
         echo "##################### apc_tom $Hmode #####################"
         echo 
         echo "Checking apache and tomcat consistency at $Hcheckdate"
         echo
         cat /root/mode/tmp/Hapc_tom$$.tmp
      } >> /root/mode/logs/apc_tom.log
   fi
   rm -f /root/mode/tmp/Hapc_tom$$.tmp
}

#

