#!/bin/bash 

#

if [ -f /var/lib/mysql/RPM_UPGRADE_HISTORY ]; then
   if [ "$1" = "-l" ]; then
      echo $(cat /var/lib/mysql/RPM_UPGRADE_HISTORY 2>/dev/null | grep -E "MySQL RPM (installation of|upgrade to) version" | sed -re "s/^.* version (...).*/\1/" | tail -n 1)
   else
      echo $(cat /var/lib/mysql/RPM_UPGRADE_HISTORY 2>/dev/null | grep -E "MySQL RPM (installation of|upgrade to) version" | sed -re "s/^.* version (...).*/\1/" | uniq) | sed -re "s/ /->/g"
   fi
elif [ -f /var/lib/mysql/mysql_upgrade_info ]; then
   echo `cat /var/lib/mysql/mysql_upgrade_info | sed -re "s/^(...).*/\1/"`
fi

#

