#!/bin/bash
# --------------------------------------------------------------------------------
# function:
#           clear linux caches 
# e.g.    :
#          ./clrcache       # enter clear cache mode according to certain criteria  
#          ./clrcache 1     # enter clear cache mode forcibly
#          ./clrcache 2     # enter clear cache mode and do clear forcibly
# --------------------------------------------------------------------------------

# check authority 

if [ "$HOME" != "/root" -a "$HOME" != "/" ]; then
   exit 1
fi

# check linux version  

if [ -x /etc/ifconfig ]; then
   exit 0
fi

# new method to check reentrance 

/root/mode/withyou $$ clrcache 1 && exit 

# 

/root/mode/.pis 

# collect data 

HTTLMEM=`free  | grep "Mem:" | sed -e "s/^Mem: *\([0-9]\{1,\}\).*/\1/"`
HUSED1=`free   | grep "Mem:" | sed -re "s/^Mem: *([0-9]+) *([0-9]+).*/\2/"`
HUSED2=`free   | grep "buffers/cache:" | sed -re "s/.*buffers\/cache: *([0-9]+).*/\1/"`
HUSED3=`free   | grep "Swap:" | sed -re "s/^Swap: *([0-9]+) *([0-9]+).*/\2/"`
HUSED1PT=`echo "$HUSED1 * 100 / $HTTLMEM" | bc`
HUSED2PT=`echo "$HUSED2 * 100 / $HTTLMEM" | bc`
HUSED3PT=`echo "($HUSED2+$HUSED3) * 100 / $HTTLMEM" | bc`
HUSED4PT=`echo "($HUSED1-$HUSED2) * 100 / $HTTLMEM" | bc`

# check data   

if [ "$1" = "1" -o "$1" = "2" ]; then
   :
elif [ $HUSED1PT -ge 88 -o $HUSED3 -gt 0 ]; then
   :
elif ps -ef | grep -E "/(s|m)(load|dump)( |$)" | grep -v grep > /dev/null; then
   :
else
   exit
fi

# 

if [ $HUSED3 -le 0 ]; then
   # ------------------------------
   # swap has not been used 
   # ------------------------------
   if [ "$1" = "2" ]; then
      # forcible clear
      echo 3 > /proc/sys/vm/drop_caches
   elif [ $HUSED1PT -ge 92 ]; then
      # -----------------------------------------------------------
      # rather high usage of memory,drop buffers/caches more often
      # -----------------------------------------------------------
      if [ $HUSED4PT -ge 1 ]; then
         echo 3 > /proc/sys/vm/drop_caches
      fi
   elif [ $HUSED1PT -ge 88 ]; then
      # ------------------------------------------
      # drop buffers/caches at large scale 
      # ------------------------------------------
      if [ $HUSED4PT -ge 3 ]; then
         echo 3 > /proc/sys/vm/drop_caches
      fi
   else
      :
   fi
else
   echo 3 > /proc/sys/vm/drop_caches
   if [ $HUSED3PT -le 96 ]; then
      # clear caches & buffers
      /root/mode/modemsg clrcache "le96 task began at `LANG=en_US;date`"
      if sync; then
         /root/mode/modemsg clrcache "sync part ended at `LANG=en_US;date`"
         echo 3 > /proc/sys/vm/drop_caches
         /root/mode/modemsg clrcache "drop part ended at `LANG=en_US;date`"
         # clear swap
         /sbin/swapoff -a && /sbin/swapon -a
         /root/mode/modemsg clrcache "swap part ended at `LANG=en_US;date`" more
      else
         /root/mode/modemsg clrcache "No sufficient memory for the workload!!!" more
      fi
   elif [ $HUSED3PT -le 99 ]; then
      # -------------------------------------------------------------------------------
      # I don't know if 'swapoff -a' will succeed
      # System administrator should stop some services,then restart them to free memory 
      # -------------------------------------------------------------------------------
      /root/mode/modemsg clrcache "No sufficient memory for the workload!!!" more
   else
      # -------------------------------------------------------------------------------
      # situation:  memory stress
      # suggestion: add system memory
      # -------------------------------------------------------------------------------
      /root/mode/modemsg clrcache "No sufficient memory for the workload!!!"
      /root/mode/modemsg clrcache "Please add system memory as soon as possible!!!" more
   fi
fi

# end of script

