#!/bin/bash 
# ------------------------------------------------------------------------
# function:
#          clear standard logs of the form "*<date>*" under directory "$1"
# usages  :
#          ./cstdlogs <logdirectory> [<reserve-days>]
# e.g.    :
#          ./cstdlogs /usr/local/apache/logs
# ------------------------------------------------------------------------

# 

[ -z "$1" ] && exit 1
[ ! -d "$1" ] && exit 1

#

HDAYS=${2:-5}
if (echo "$HDAYS"  | grep -E  "^[0-9]+$" > /dev/null); then
   if [ $HDAYS -lt 2 ]; then
      echo "Parameter should be integer greater than one!" && exit 1
   fi
else
   echo "invalid parameter" && exit 1
fi

#

HDDATE=`date -d "-$HDAYS days" +%Y-%m-%d`

#

cd "$1"
Htestvars=`ls -1|grep -E '[0-9]{4}-[0-9]{2}-[0-9]{2}'|sed -re "s/^/b/" -e "s/$/e/"`
while read -r k; do
   j=`echo "$k" | sed -re "s/^b(.*)e$/\1/"`
   if [ -d "$j" ]; then
      continue
   fi
   Hjdate=`echo "$j" | sed -re "s/^.*([0-9]{4}-[0-9]{2}-[0-9]{2}).*$/\1/"`
   if [ "$Hjdate" \< "$HDDATE" -o "$Hjdate" = "$HDDATE" ]; then
      rm -f "$j"
   fi
done <<<"$Htestvars"

# end


