#!/bin/bash 
# ---------------------------------------------------------------------
# function:
#          mode db dumpname generator
# notes   :
#          Exclusive PV operation is required  
# ---------------------------------------------------------------------

# check exclusiveness

if /root/mode/withyou $$ dumpnamepv; then
   echo
   exit 
fi

# now,I'm the only one

HDBNAME="$1"
HCDATE="$2"

cd /root/mode/dump
if [ `ls -1 $HDBNAME-${HCDATE}_[0-9][0-9][0-9].sql 2>/dev/null| wc -l` -gt 0 ]; then
   HINDEX=`ls -1 $HDBNAME-${HCDATE}_[0-9][0-9][0-9].sql 2>/dev/null|sort -r|sed -n "1 p"|sed -re "s/^.*([0-9]{3}).sql$/\1/"`
   HINDEX=$[1001+$[10#$HINDEX]]
   HINDEX=${HINDEX:(-3)}
   if [ $HINDEX -eq 0 ]; then
      HINDEX='001'
   fi
else
   HINDEX='001'
fi
HDUMPNAME="/root/mode/dump/$HDBNAME-${HCDATE}_$HINDEX.sql"
touch "$HDUMPNAME"
echo  "$HDUMPNAME"

# end

