#!/bin/bash
# ------------------------------------------------------------
# function: get active ips 
# ------------------------------------------------------------

/sbin/ifconfig | grep "inet addr:.*Bcast" | sed -re "s/.*inet addr:([^ ]+).*/\1/"
