#!/bin/bash
# ------------------------------------------------------------------
# function:
#          get the category and various attributes of a tomcat 
# usages  :
#          ./gettomp <tomcat>
# ------------------------------------------------------------------

#

/root/mode/check_tomcat $1 || exit 1

#

cd /usr/local/$1/conf
Hhtpp=$(cat /usr/local/$1/conf/server.xml|grep -E "<Connector port=\"[0-9]+\" protocol=\"HTTP/1.1\"" | grep -v SSL | sed -re "s/.*\"([0-9]+)\" proto.*/\1/")
Hhtpp="$Hhtpp     "
Hhtpp=${Hhtpp:0:5}
Hajpp=$(cat /usr/local/$1/conf/server.xml|grep -E "<Connector port=\"([0-9]+)\" protocol=\"AJP" | sed -re "s/.*\"([0-9]+)\" p.*/\1/")
Hdwnp=$(cat /usr/local/$1/conf/server.xml|grep -E "<Server port=\"([0-9]+)\" shutdown=" | sed -re "s/.*\"([0-9]+)\".*/\1/")
Hjmxp=`echo $Hdwnp | sed -re "s/^./7/"`
if [ -f /etc/.mode_Ifeelscared ]; then
   Hports="H ${Hhtpp}A $Hajpp D $Hdwnp J $Hjmxp"
else
   Hports="H ${Hhtpp}A $Hajpp D $Hdwnp"
fi
if /root/mode/isctom $1; then
   Hclup=$(cat /usr/local/$1/conf/server.xml|tr -d "\r\n" | sed -re "s/.*port=\"([0-9]+)\"[ \t]*autoB.*/\1/")
   Hports="$Hports C $Hclup "
   if ! cat server.xml | grep -E "<!-- apache[1-9] -->" >/dev/null; then
      Hapctom=apache
      echo -n "apache "
   else
      Hapctom=`cat server.xml | grep -E "<!-- apache[1-9]? -->" | sed -re "s/.*<!-- (apache[1-9]?) -->.*/\1/" | head -n 1`
      echo -n $Hapctom
   fi
   Hapctom=`echo $Hapctom | sed -re "s/apache/build/"`
else
  Hapctom=$1
  Hports="$Hports ......."
  if ! /root/mode/isNtom $1; then
       echo -n "single "
  else
      echo -n "Single "
  fi
fi
if [ ${#1} -le 10 ]; then
   Htom="$1          "
   Htom=${Htom:0:10}
else
   Htom="$1"
fi

# get the apps 

Htomapps=`ls -1d  /usr/local/$1/*/*/WEB-INF/ 2>/dev/null | grep -Ev "/(ROOT|docs|examples|host-manager|manager)/WEB-INF/$" | 
          sed -re "s/\/WEB-INF\/$//" | sort | sed -r -e "s/^\/usr\/local\/$1\///" -e "s/^webapps\///" -e "s/\//./"`
Htomsapps=`echo \($Htomapps\)`
if echo $Htomsapps | grep -E ipmsthef >/dev/null; then
   if /root/mode/mod_config /root/antDep/$Hapctom.properties "thekmark" "#Get#" | grep -E "^[yYtT]" >/dev/null; then
      Htomsapps=`echo $Htomsapps | sed -re "s/thef/thek/g"`
   fi
fi
if [ ${#Htomsapps} -le 47 ]; then
   Htomsapps="$Htomsapps............................................."
   Htomsapps=${Htomsapps:0:47}
fi
#
echo " $Htom $Htomsapps ${Hports}...... `/root/mode/tctomcat $1 2>/dev/null`"


