#!/bin/bash
# ---------------------------------------------------------------
# Install tomcat 
#                                      -----hry-----
# ---------------------------------------------------------------

# Install tomcat

# installation mode

if [ -z "$1" -o "$1" = "apache" ]; then
   HTOMMODE=c
   HAPACHEMODE=apache
elif echo "$1" | grep -E "^apache[1-7]$" >/dev/null; then
   HTOMMODE=c
   HAPACHEMODE=$1
elif [ "$1" = "Nonclustertomcat" ]; then
   HTOMMODE=N
elif [ "$1" = "nonclustertomcat" ]; then
   Htom_utf8=1
   Htom_docb=w
   HTOMMODE=n
elif [ "$1" = "w" ]; then
   Htom_utf8=1
   Htom_docb=w
   HTOMMODE=n
elif [ "$1" = "W" ]; then
   Htom_utf8=1
   Htom_docb=w
   HTOMMODE=N
elif [ "$1" = "m" ]; then
   Htom_utf8=1
   Htom_docb=m
   HTOMMODE=n
elif [ "$1" = "M" ]; then
   Htom_utf8=1
   Htom_docb=m
   HTOMMODE=N
elif [ "$1" = "p" ]; then
   Htom_utf8=1
   Htom_docb=p
   HTOMMODE=n
elif [ "$1" = "P" ]; then
   Htom_utf8=1
   Htom_docb=p
   HTOMMODE=N
elif echo "$1" | grep -E "^[nN]?(utf8)?$" >/dev/null; then
   if echo "$1" | grep -E "^N" >/dev/null; then 
      HTOMMODE=N
   else
      HTOMMODE=n
   fi
   if echo "$1" | grep -E "utf8$" >/dev/null; then 
      Htom_utf8=1
   fi
else
   exit
fi

# check limit

if [ "$HTOMMODE" = "c" ]; then
   if [ -z "$Hinst_Ctom" ]; then
      exit 1
   fi
   if [ "$HCTOMMORE" = "yes" ]; then
      # limit to 3 
      [ `/root/mode/ctomno -c $HAPACHEMODE` -ge 3 ] && exit 1
   else
      # limit to 2 
      [ `/root/mode/ctomno -c $HAPACHEMODE` -ge 2 ] && exit 1
   fi
else
   Hntomno=$[`/root/mode/ctomno -n`+`/root/mode/ctomno -N`]

   # limit to 5 for the moment 
 
   [ $Hntomno -ge 8 ] && exit 1

   # confirm 

   if [ $Hntomno -gt 0 ]; then
      if [ $Hntomno -gt 1 ]; then
         /root/mode/modemsg inst_tomcat "$Hntomno noncluster tomcats have been installed!"
      else
         /root/mode/modemsg inst_tomcat "$Hntomno noncluster tomcat has been installed!"
      fi
      /root/mode/confirm "Are you sure to install another noncluster tomcat at this machine" || exit 1 
   else
      /root/mode/confirm "Are you sure to install a noncluster tomcat at this machine" || exit 1 
   fi

   # install java jdk

   /root/mode/inst_java

   # set path

   /root/mode/setpath

   # 

   if ! cat /etc/sysctl.conf 2>/dev/null | grep -E "conntrack_tcp_loose" >/dev/null; then
      /root/mode/modemsg inst_tomcat "Installing basic mode configurations ..." more
      /root/mode/inst_com
   fi

fi

# antdep

[ -d /root/antDep ] ||
{
cd /
tar xzvf /root/packages/antdep.tar.gz
}

#

if [ "$HTOMMODE" = "c" ]; then
   Htomloop=6
   while [ 1 -eq 1 ]; do
      if [ -d /usr/local/tomcat$Htomloop ]; then
         if [ $Htomloop -eq 6 ]; then
            Htomloop=602
         else
            Htomloop=$[$Htomloop+1]
         fi
      else
         break
      fi
   done
   if [ $Htomloop -eq 6 ]; then
      Htomtail=6
      Hportoffset=1
   else
      Htomtail=$Htomloop
      Hportoffset=$[$Htomloop-600]
   fi
else
   Htomloop=1
   while [ 1 -eq 1 ]; do
      if [ -d /usr/local/tomcat$Htomloop ]; then
         Htomloop=$[$Htomloop+1]
      elif [ $Htomloop -eq 6 ]; then
         Htomloop=$[$Htomloop+1]
      else
         break
      fi
   done
   Htomtail=$Htomloop
   Hportoffset=$[$Htomloop+20]
fi

# mkdir tmp directory

Hhrytmpdir="/root/mode/hhrytmpdir$$"
Hhrytmpfi1="/root/mode/tmp/hhrytmpfi1$$"
Hhrytmpfi2="/root/mode/tmp/hhrytmpfi2$$"

mkdir -p $Hhrytmpdir
cd $Hhrytmpdir
rm -fR *

# 

tar xzvf /root/packages/tomcat6.tar.gz
mv `ls` tomcat$Htomtail
cp -fR tomcat$Htomtail /usr/local

#

cat /usr/local/tomcat$Htomtail/conf/server.xml |
sed -re "s/8005/$[8004+$Hportoffset]/g" |
if [ "$HTOMMODE" = "c" ]; then
   sed -re "s/8080/$[9079+$Hportoffset]/g"
else
   sed -re "s/8080/$[8079+$Hportoffset]/g"
fi  |
sed -re "s/(port=\")8009(\" protocol=\"AJP\/1\.3\")/\1$[9008+$Hportoffset]\2/g" > $Hhrytmpfi1
cp -f $Hhrytmpfi1 /usr/local/tomcat$Htomtail/conf/server.xml 

cd $Hhrytmpdir
rm -fR *

# configure cluster

. /root/mode/getmcast $HAPACHEMODE

# --------------------------------------------------------
# mode configured cluster segment
# DON'T change any of them
# --------------------------------------------------------

cat > $Hhrytmpfi1 << EOF
        <!-- $HAPACHEMODE -->
        <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"
                 channelSendOptions="6">

          <Manager className="org.apache.catalina.ha.session.DeltaManager"
                   expireSessionsOnShutdown="false"
                   notifyListenersOnReplication="true"/>

          <Channel className="org.apache.catalina.tribes.group.GroupChannel">
            <Membership className="org.apache.catalina.tribes.membership.McastService"
                      address="$HHRYMCAST"
                      port="$HHRYMPORT"
                      frequency="500"
                      dropTime="6000"/>

            <Receiver className="org.apache.catalina.tribes.transport.nio.NioReceiver"
                      address="localhost"
                      port="4000"
                      autoBind="100"
                      selectorTimeout="5000"
                      maxThreads="6"/>

            <Sender className="org.apache.catalina.tribes.transport.ReplicationTransmitter">
              <Transport className="org.apache.catalina.tribes.transport.nio.PooledParallelSender"/>
            </Sender>
            <Interceptor className="org.apache.catalina.tribes.group.interceptors.TcpFailureDetector"/>
            <Interceptor className="org.apache.catalina.tribes.group.interceptors.MessageDispatch15Interceptor"/>
            <Interceptor className="org.apache.catalina.tribes.group.interceptors.ThroughputInterceptor"/>
          </Channel>
          <Valve className="org.apache.catalina.ha.session.JvmRouteBinderValve" enabled="true" sessionIdAttribute="takeoverSessionid"/>
          <ClusterListener className="org.apache.catalina.ha.session.ClusterSessionListener"/>
          <ClusterListener className="org.apache.catalina.ha.session.JvmRouteSessionIDBinderListener"/>
        </Cluster>   
EOF

cd /usr/local/tomcat$Htomtail/conf
if [ "$HTOMMODE" = "c" ]; then
   cat server.xml | grep -E "</Cluster>" >/dev/null ||
   {
   Hhrycline=`cat server.xml | sed -n -re "/<Cluster className=\"org.apache.catalina.ha.tcp.SimpleTcpCluster\"\/>/ ="`
   Hhrycline=`expr $Hhrycline + 1`
   cat /usr/local/tomcat$Htomtail/conf/server.xml |
   sed -re "$Hhrycline r $Hhrytmpfi1" | 
   sed -re "s/4000/$[3999+$Hportoffset]/g" | 
   sed -re "s/<(Engine name=\"Catalina\" defaultHost=\"localhost\")>/<\1 jvmRoute=\"tomcat$Htomtail\">/" > $Hhrytmpfi2
   cat $Hhrytmpfi2 > /usr/local/tomcat$Htomtail/conf/server.xml 
   }
else
   # utf8 setting
   if [ "$Htom_utf8" = "1" ]; then
      cat /usr/local/tomcat$Htomtail/conf/server.xml |
      sed -re "s/$/HrYhByHsC/" |
      tr -d "\n" | 
      sed -re "s/(redirectPort=\"[0-9]*\" )/\1URIEncoding=\"UTF-8\" useBodyEncodingForURI=\"true\"/1" |
      sed -re "s/HrYhByHsC/\n/g" > $Hhrytmpfi2
      cat $Hhrytmpfi2 > /usr/local/tomcat$Htomtail/conf/server.xml 
   fi
   # docBase setting
   if [ "$Htom_docb" = "w" ]; then
      cat /usr/local/tomcat$Htomtail/conf/server.xml | 
      sed -re "/<\/Host>/ i\        <Context docBase=\"\/usr\/local\/tomcat$Htomtail\/webapps\/website\/\" path=\"\" />" > $Hhrytmpfi2
      cat $Hhrytmpfi2 > /usr/local/tomcat$Htomtail/conf/server.xml 
   elif [ "$Htom_docb" = "m" ]; then
      cat /usr/local/tomcat$Htomtail/conf/server.xml | 
      sed -re "/<\/Host>/ i\        <Context docBase=\"\/usr\/local\/tomcat$Htomtail\/webapps\/mobilepms\/\" path=\"\" reloadable=\"true\"/>" > $Hhrytmpfi2
      cat $Hhrytmpfi2 > /usr/local/tomcat$Htomtail/conf/server.xml 
   elif [ "$Htom_docb" = "p" ]; then
      cat /usr/local/tomcat$Htomtail/conf/server.xml |
      sed -re "/<\/Host>/ i\        <Context docBase=\"\/home\/pos\/\" path=\"\/pluPhoto\" />" > $Hhrytmpfi2
      cat $Hhrytmpfi2 > /usr/local/tomcat$Htomtail/conf/server.xml
   fi
   # memory mode
   if [ "$HTOMMODE" = "N" ]; then
      cat server.xml | grep -E "<!-- ModeN mark -->" >/dev/null ||
      {
      cat /usr/local/tomcat$Htomtail/conf/server.xml |
      sed -re "/<\/Host>/ i\        <!-- ModeN mark -->" > $Hhrytmpfi2
      cat $Hhrytmpfi2 > /usr/local/tomcat$Htomtail/conf/server.xml 
      }
   fi
fi

# add maxthread setting etc.

/root/mode/mod_tthread "tomcat$Htomtail"

#
  
cd $Hhrytmpdir
rm -fR *

# delete tmp file and directory

cd /root/mode
rm -fR $Hhrytmpdir
rm -f  $Hhrytmpfi1
rm -f  $Hhrytmpfi2

# 

/root/mode/inst_gcserver

#


