#!/bin/bash
# ------------------------------------------------------------------------------------------------------------------
# function:
#           load database
# usage   :
#           ./mload [<mysql-server-ip>] <database> <userfile.sql>|<xxx.tar.gz>
#           ./mload [<mysql-server-ip>] <database> <dump-database> [|<date>|<date>/<index>|<index>]
# e.g.    :
#           ./mload       portal_tr /tmp.sql            
#           ./mload       portal_tr portal      
#           ./mload       portal_tr portal 2011-12-18     
#           ./mload       portal_tr portal 2011-12-18/     
#           ./mload       portal_tr portal /1         
#           ./mload       portal_tr portal 2011-12-18/1          
#           ./mload       portal_tr portal 18/1          
#           ./mload       portal_tr portal /1          
#           ./mload       portal_tr portal 18/          
#           ./mload       portal_tr portal 9          
#           ./mload -q    portal portal          
#           ./mload -f    portal portal          
#           ./mload -q -f portal portal          
# ------------------------------------------------------------------------------------------------------------------

# get options

HOPTIONS=""
while (echo "'$1'"  | grep -E  -e "^'-" > /dev/null)
do
   HOPTIONS="$HOPTIONS$1"
   shift
done

# get mysql server ip

. /root/mode/mysqldip

# Default database to load is portal_tr

HDBNAME=${1:-portal_tr}
HDBNAME=`echo "$HDBNAME" | tr "A-Z" "a-z"`

# $HDBNAME must exist 

if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show databases like '$HDBNAME'"|grep -i "^$HDBNAME"` ]; then
   echo "Database $HDBNAME doesn't exist at $HMYSQLDIP2!" && exit 1
fi

# dump name

HDUMP="${2:-$HDBNAME}"

HISTAR=0
if echo "$HDUMP" | grep -E "(\.tar\.gz|\.sql)$" >/dev/null; then
   # sql file or tar.gz file
   if [ ! -f "$HDUMP" ]; then
      echo "File $HDUMP doesn't exist!" && exit 1
   else
      if echo "$HDUMP" | grep -E "\.sql$" >/dev/null; then
         # sql file
         HDUMPNAME="$HDUMP"
      else
         # tar.gz file
         HISTAR=1
         HTMPSQLDIR="/root/mode/tmp/tmptardir$$"
         mkdir -p $HTMPSQLDIR
         rm -fR $HTMPSQLDIR/*
         tar xzvf "$HDUMP" -C $HTMPSQLDIR >/dev/null 2>&1
         HSQLCNT=`find $HTMPSQLDIR -name "*.sql" | grep -E "\.sql$" | wc -l`
         if [ "$HSQLCNT" -eq 0 ]; then
            echo "No sql file in $HDUMP!" 
            rm -fR $HTMPSQLDIR
            exit 1
         elif [ "$HSQLCNT" -gt 1 ]; then
            echo "More than one sql files in $HDUMP!"
            rm -fR $HTMPSQLDIR
            exit 1
         fi
         HDUMPNAME=`find $HTMPSQLDIR -name "*.sql" | grep -E "\.sql$"`
      fi
   fi
else
   cd /root/mode/dump
   HDUMPCNT=`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9][0-9].sql 2>/dev/null | wc -l`
   if [ $HDUMPCNT -eq 0 ]; then
      echo "No $HDUMP standard dumps exist in  /root/mode/dump directory" && exit 1
   fi
   if echo "$3" | grep -E "^$" >/dev/null; then
      # no date or index
      HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9][0-9].sql 2>/dev/null | tail -n 1`
   elif echo "$3" | grep -E "^[0-9]{4}-[0-9]{2}-[0-9]{2}[/]?$" >/dev/null; then
      # pass
      # complete date only
      HDATE=$(echo "$3" | sed -re "s/^([^\/]*).*$/\1/")
      HDUMPCNT=`ls -1 $HDUMP-${HDATE}_[0-9][0-9][0-9].sql 2>/dev/null | wc -l`
      if [ $HDUMPCNT -eq 0 ]; then
         echo "No $HDUMP standard dumps of date $HDATE exist in /root/mode/dump directory" && exit 1
      fi
      HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-${HDATE}_[0-9][0-9][0-9].sql 2>/dev/null | tail -n 1`
   elif echo "$3" | grep -E "^[0-9]{1,2}/[0-9]{1,}$" >/dev/null; then
      # pass
      # day part and index
      HDAY=$(echo "$3" | sed -re "s/^(.*)\/.*$/\1/")
      HINDEX=$(echo "$3" | sed -re "s/^.*\/(.*)$/\1/")
      if [ $HDAY -gt 31 ]; then
           echo "Invalid parameter $3" && exit 1
      elif [ $HDAY -lt 1 ]; then
           echo "Invalid parameter $3" && exit 1
      fi
      HDAY=$[100+$[10#$HDAY]]
      HDAY=${HDAY:(-2)}
      HINDEX=$[1000+$[10#$HINDEX]]
      HINDEX=${HINDEX:(-3)}
      HDUMPCNT=`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_$HINDEX.sql 2>/dev/null | wc -l`
      if [ $HDUMPCNT -eq 0 ]; then
         echo "No $HDUMP standard dumps of day $HDAY and index $HINDEX exist in /root/mode/dump directory" && exit 1
      fi
      HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_$HINDEX.sql 2>/dev/null|tail -n 1`
   elif echo "$3" | grep -E "^[0-9]{1,2}/$" >/dev/null; then
      # pass
      # day part only
      HDAY=$(echo "$3" | sed -re "s/^(.*)\/$/\1/")
      if [ $HDAY -gt 31 ]; then
           echo "Invalid parameter $3" && exit 1
      elif [ $HDAY -lt 1 ]; then
           echo "Invalid parameter $3" && exit 1
      fi
      HDAY=$[100+$[10#$HDAY]]
      HDAY=${HDAY:(-2)}
      HDUMPCNT=`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_[0-9][0-9][0-9].sql 2>/dev/null | wc -l`
      if [ $HDUMPCNT -eq 0 ]; then
         echo "No $HDUMP standard dumps of day $HDAY exist in /root/mode/dump directory" && exit 1
      fi
      HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_[0-9][0-9][0-9].sql 2>/dev/null|tail -n 1`
   elif echo "$3" | grep -E "^/[0-9]{1,}$" >/dev/null; then
      # pass
      # index only
      HINDEX=${3:1}
      HINDEX=$[1000+$[10#$HINDEX]]
      HINDEX=${HINDEX:(-3)}
      HDUMPCNT=`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_$HINDEX.sql 2>/dev/null | wc -l`
      if [ $HDUMPCNT -eq 0 ]; then
         echo "No $HDUMP standard dumps of index $HINDEX exist in /root/mode/dump directory" && exit 1
      fi
      HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_$HINDEX.sql 2>/dev/null | tail -n 1`
   elif echo "$3" | grep -E "^[0-9]{1,}$" >/dev/null; then
      # day or index 
      HDAY=$[100+$[10#$3]]
      HDAY=${HDAY:(-2)}
      HINDEX=$[1000+$[10#$3]]
      HINDEX=${HINDEX:(-3)}
      HDUMPCNT1=`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_[0-9][0-9][0-9].sql 2>/dev/null | wc -l`
      HDUMPCNT2=`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_$HINDEX.sql 2>/dev/null | wc -l`
      if [ $HDUMPCNT1 -eq 0 -a $HDUMPCNT2 -eq 0 ]; then
         echo "No $HDUMP standard dumps of day(or index) $3 exist in /root/mode/dump directory" && exit 1
      elif [ $HDUMPCNT1 -gt 0 -a $HDUMPCNT2 -eq 0 ]; then
         # day match only
         HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_[0-9][0-9][0-9].sql 2>/dev/null|tail -n 1`
      elif [ $HDUMPCNT1 -eq 0 -a $HDUMPCNT2 -gt 0 ]; then
         # index match only
         HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_$HINDEX.sql 2>/dev/null | tail -n 1`
      else
         # match both,must be unique
         HDUMPCNT3=`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_$HINDEX.sql 2>/dev/null | wc -l`
         if [ $HDUMPCNT3 -eq 0 ]; then
            echo "Ambiguous match of dumps" && exit 1
         else
            HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-[0-9][0-9][0-9][0-9]-[0-9][0-9]-${HDAY}_$HINDEX.sql 2>/dev/null | tail -n 1`
         fi
      fi
   elif echo "$3" | grep -E "^[0-9]{4}-[0-9]{2}-[0-9]{2}/[0-9]{1,}$" >/dev/null; then
      # complete date and index
      HDATE=`echo $3 | sed -re "s/^(.*)\/.*/\1/"`
      HINDEX=`echo $3 | sed -re "s/^.*\/(.*)/\1/"`
      HINDEX=$[1000+$[10#$HINDEX]]
      HINDEX=${HINDEX:(-3)}
      HDUMPCNT=`ls -1 $HDUMP-${HDATE}_$HINDEX.sql 2>/dev/null | wc -l`
      if [ $HDUMPCNT -eq 0 ]; then
         echo "No $HDUMP standard dumps of $HDATE/$HINDEX exist in /root/mode/dump directory" && exit 1
      fi
      HDUMPNAME=/root/mode/dump/`ls -1 $HDUMP-${HDATE}_$HINDEX.sql 2>/dev/null | tail -n 1`
   else
      echo "Invalid parameter $3" && exit 1
   fi
fi

# check sql dump completeness

if ! /root/mode/comdump "$HDUMPNAME"; then
   /root/mode/modemsg mload "Incomplete sql dump $HDUMPNAME!"
   [ $HISTAR -eq 1 ] && rm -fR "$HTMPSQLDIR"
   exit 1 
fi

#  

HDBNAME_mon=$HDBNAME
Hdbs_reglist=`cat $HDUMPNAME 2>/dev/null | head -n 40 | grep -E "^# mode reg_db_list::" | sed -re "s/^# mode reg_db_list::(.*)/\1/"` 
if [ -n "$Hdbs_reglist" ]; then
   # MySQL server version at $HMYSQLDIP
   Hdbs_MySQL_ver1=`/root/mode/seecfg -s $HMYSQLDIP  "show variables like 'version'" | sed -re "s/^.*\t(.*)/\1/"`
   Hdbs_MySQL_vcm1=`/root/mode/seecfg -s $HMYSQLDIP  "show variables like 'version_comment'" | sed -re "s/^.*\t(.*)/\1/"`
   # MySQL server version in dump $HDUMPNAME
   Hdbs_MySQL_ver2=`cat $HDUMPNAME 2>/dev/null | head -n 40 | grep -E "^# mode MySQL Ver::::" | sed -re "s/^# mode MySQL Ver::::(.*)/\1/"`
   Hdbs_MySQL_vcm2=`cat $HDUMPNAME 2>/dev/null | head -n 40 | grep -E "^# mode MySQL VerC:::" | sed -re "s/^# mode MySQL VerC:::(.*)/\1/"`
   # MySQL server version check  
   if [ "$Hdbs_MySQL_ver1" != "$Hdbs_MySQL_ver2" -o "$Hdbs_MySQL_vcm1" != "$Hdbs_MySQL_vcm2" ]; then
      /root/mode/modemsg mload " MySQL server version check failed!" more
      exit 1
   fi 
   if [ `/root/mode/seecfg -s $HMYSQLDIP "show processlist" | wc -l` -ge 2 ]; then
      /root/mode/modemsg mload "There shoud be no other conections to MySQL server at $HMYSQLDIP2!" more
      exit 1
   fi
   if [ `/root/mode/traceps "crond"` != 'suc' ]; then
      # confirmation
      /root/mode/confirm "Are you sure to load '$HDUMPNAME' into MySQL server at $HMYSQLDIP2" hellohby || 
      {
         [ $HISTAR -eq 1 ] && rm -fR "$HTMPSQLDIR"
         exit 1 
      }
   fi
   HDBNAME_mon="$Hdbs_reglist"
elif [ "$HDBNAME" = 'mysql' -o "$HDBNAME" = 'performance_schema' ]; then
   # system database check
   if ! echo "$HOPTIONS" | grep -E -e "(-S)(-|$)" >/dev/null; then
      /root/mode/modemsg mload "You must use the -S option to load '$HDBNAME' at $HMYSQLDIP2!" more
      exit 1
   elif ! echo "$HDUMPNAME" | grep -E "^(.*/)?$HDBNAME-[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{3}\.sql" >/dev/null; then
      /root/mode/modemsg mload "Dump file '$HDUMPNAME' is not a mode standard dump of $HDBNAME!" more
      exit 1
   elif [ "$HMYSQLDIP" != 'localhost' ]; then
      /root/mode/modemsg mload "System database can only be loaded using localhost!" more
      exit 1
   elif [ `/root/mode/seecfg -s $HMYSQLDIP "show processlist" | wc -l` -ge 2 ]; then
      /root/mode/modemsg mload "There shoud be no other conections!" more
      exit 1
   fi
   # confirmation
   /root/mode/confirm "Are you sure to load '$HDUMPNAME' into database $HDBNAME at $HMYSQLDIP2" hellohby || 
   {
      [ $HISTAR -eq 1 ] && rm -fR "$HTMPSQLDIR"
      exit 1 
   }
else
   # load confirmation for user databases unless load is done with crontab task
   if [ `/root/mode/traceps "crond"` != 'suc' ]; then
      # db connection check 
      if ! echo "$HOPTIONS" | grep -E -e "(-f)(-|$)" >/dev/null; then
         # not in force mode
         if [ `/root/mode/seecfg -s $HMYSQLDIP "show processlist" | grep -Pi "\t$HDBNAME\t" | wc -l` -ge 1 ]; then
            /root/mode/modemsg mload "Database '$HDBNAME' at $HMYSQLDIP2 seems in use!mload will not continue." more
            exit 1
         fi
      fi
      # confirmation
      /root/mode/confirm "Are you sure to load '$HDUMPNAME' into database $HDBNAME at $HMYSQLDIP2" hellohby || 
      {
         [ $HISTAR -eq 1 ] && rm -fR "$HTMPSQLDIR"
         exit 1 
      }
   fi
fi 

# clear linux caches before load process

/root/mode/clrcache 1

# load process

{
echo
echo "############# mload $HOPTIONS $HMYSQLDIP2 $* #############"
echo
echo "Load database $HDBNAME at $HMYSQLDIP2 from $HDUMPNAME at `LANG=en_US;date`"

# load at background

if echo "$HOPTIONS" | grep -E -e "(-nsqllogbin|-nosqllogbin|-q)(-|$)" >/dev/null; then
   export HNoBiNlOg=DaNgEr
fi
/root/mode/seecfg $HMYSQLDIP "$HDUMPNAME" $HDBNAME &
Hlprocess=$!
/usr/bin/renice -5 $Hlprocess &>/dev/null

# monitor load process

echo
echo -n "^-^"
while [ 1 ];do
   sleep 5
   /root/mode/monload $Hlprocess $HMYSQLDIP $HDBNAME_mon || break
done
echo -n "^-^"
echo

#

echo
echo "Load ended at `LANG=en_US;date`"
echo
} 2>&1 | tee -a /root/mode/logs/dumpload.log

# rm tmp directory

[ $HISTAR -eq 1 ] && rm -fR $HTMPSQLDIR

# clear linux caches after load process

/root/mode/clrcache 1

#

