#!/bin/bash
# ------------------------------------
# get mysql server ip 
# ------------------------------------

if [ "$1" = "localhost" ]; then
   HMYSQLDIP=$1
   shift
elif echo "$1" | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" >/dev/null; then
   HMYSQLDIP=`/root/mode/nmlizeip "$1"`
   shift
elif echo "$1" | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" >/dev/null; then
   HMYSQLDIP=`/root/mode/gsip "$1"`
   [ "$HMYSQLDIP" ] && shift
elif echo "$1" | grep -E "^[0-9]{1,3}\.[0-9]{1,3}$" >/dev/null; then
   HMYSQLDIP=`/root/mode/gsip "$1"`
   [ "$HMYSQLDIP" ] && shift
elif echo "$1" | grep -E "\.sql$" >/dev/null; then
   :
elif [ -d "$1" ]; then
   :
elif echo "$1" | grep -E "^([a-zA-Z0-9_-]+\.)+[a-zA-Z0-9_-]+$" >/dev/null; then
   # considered to be domain name
   HMYSQLDIP=`echo "$1" | tr "A-Z" "a-z"`
   shift 
fi
if [ -z "$HMYSQLDIP" ]; then
   if [ -f /root/antDep/build.properties ]; then
      HMYSQLDIP=`cat /root/antDep/build.properties | grep -E "^db\.root=" | tr -d "\r" |  sed -re "s/^.*=(.*)/\1/"`
   elif [ -x /usr/sbin/mysqld ]; then
      HMYSQLDIP=localhost
   else 
      HMYSQLDIP=192.168.0.230
   fi
fi
if [ "$HMYSQLDIP" = "localhost" -o "$HMYSQLDIP" = "127.0.0.1" ]; then
   HMYSQLDIP1=`/root/mode/getips | sed -n "1 p"`
   HMYSQLDIP2="$HMYSQLDIP($HMYSQLDIP1)"
else
   HMYSQLDIP1=$HMYSQLDIP
   HMYSQLDIP2=$HMYSQLDIP
fi

#

if [ -f /etc/.modepass ]; then
   if cat /etc/.modepass | grep -E "^$HMYSQLDIP(\([0-9]+\)\([^:\)]+\))?:" > /dev/null; then
      Hmpline=`cat /etc/.modepass | grep -E "^$HMYSQLDIP(\([0-9]+\)\([^:\)]+\))?:" | sed -n "$ p"`
      Hfp=`echo $Hmpline | sed -re "s/^([^:]*):(.*)/\2/"`
      Hmp1=`echo $Hmpline | sed -re "s/^([^:]*):(.*)/\1/"`
      if echo $Hmp1 | grep -E "\(" >/dev/null; then
         Hmp2=`echo $Hmp1 | sed -re "s/$HMYSQLDIP(.*)/\1/"`
         Hmpport=`echo $Hmp2 | sed -re "s/^(\(([^()]+)\))(\(([^()]+)\))$/\2/"`
         Hmpuser=`echo $Hmp2 | sed -re "s/^(\(([^()]+)\))(\(([^()]+)\))$/\4/"`
         Hfp="$Hfp -u$Hmpuser -P$Hmpport" 
      fi
   else
      Hfp=deviskaifa
   fi
else
   Hfp=deviskaifa
fi

#

if [ "$Hmysql_force" = 'YeS' ]; then
   Hmodepass="-p$Hfp -f"
else
   Hmodepass="-p$Hfp"
fi

#
