#!/bin/bash
# ----------------------------------------------------
# function: show the full path of me
#
# ----------------------------------------------------

Hhry="$0"
while [ -h "$Hhry" ]; do
   Hfil=`ls -l $Hhry 2>/dev/null | sed -re "s/.*-> ([^ ]+) */\1/"`
   if echo "$Hfil" | grep "^/" >/dev/null; then
      Hhry="$Hfil"
   else
      Hhry=`dirname "$Hhry"`/"$Hfil"
   fi
done
Hdir=`dirname $Hhry`
Hfil=${Hhry#$Hdir/}
cd -P $Hdir
Hdir=`pwd`
#echo $Hdir/$Hfil
echo $Hdir



