#!/bin/bash
# -----------------------------------------------------------------------
# functions:
#           display table and its columns 
# usage    :
#           ./tabprop [<mysql-server-ip>] <dbname> <tablename> <dispmode>
# -----------------------------------------------------------------------

# get mysql server ip

. /root/mode/mysqldip 

# 

HDBNAME=${1:-targetdb2}
HDBNAME=`echo "$HDBNAME" | tr "A-Z" "a-z"`
HTABNAME=${2:-pccode}

# $HDBNAME must exist 

if [ -z `/root/mode/seecfg -s $HMYSQLDIP "show databases like '$HDBNAME'"|grep -i "^$HDBNAME"` ]; then
  /root/mode/modemsg tabprop "Database $HDBNAME doesn't exist!" more && exit 1
fi

# $HTABNAME must exist 

HTABTEST=`/root/mode/seecfg -s $HMYSQLDIP "show tables from \\\`$HDBNAME\\\` like '$HTABNAME'"|grep -i "^$HTABNAME"`
if [ -z "$HTABTEST" ]; then
   /root/mode/modemsg tabprop "Table $HTABNAME doesn't exist!" more && exit 1
fi

# 

/root/mode/seecfg -s $HMYSQLDIP "show columns from \`$HTABNAME\` from \`$HDBNAME\`" | 
sed -re "s/^([^\t]+).*/\1/g" | 
if [ "$3" = "null" ]; then
   sed -re "s/(.*)/ifnull\(\`\1\`,'##'\),/"
elif   [ "$3" = "1" ]; then
   sed -r -e "s/^/\[$HTABNAME\./g" -e "s/$/\]/g"
elif [ "$3" = "0" ]; then
   sed -re "s/$/\\+/g"
elif [ "$3" = "2" ]; then
   sed -re "s/$/\,/g"
elif [ "$3" = "2a" ]; then
   sed -r -e "s/^/a\./g" -e "s/$/\,/g"
elif [ "$3" = "2b" ]; then
   sed -r -e "s/^/b\./g" -e "s/$/\,/g"
else
   sed -r -e "s/^/\[$HDBNAME\.$HTABNAME\./g" -e "s/$/\]/g"
fi |  
sed -e "$ s/,$//" | tr -d "\n"

# end



