#!/bin/bash
# ------------------------------------------------------------------------------------------------------------------
# function:
#          test if a field string is an index expression
# usages  :
#          ./testkey <tablename> "<test-field-list>" <dbname>
# e.g.    :
#          ./testkey master_shot id portal
#          ./testkey master_shot "hotel_group_id,hotel_id,master_type,master_id,biz_date_end,biz_date_begin" portal
# -----------------------------------------------------------------------------------------------------------------

#

. /root/mode/mysqldip 

HTAB="$1"
HIND="$2"
HDB="$3"
HIND=`echo "$HIND" | tr 'A-Z' 'a-z'`

# table index information

Hindex=$(/root/mode/seecfg -s $HMYSQLDIP "show create table \`$HTAB\`" $HDB | sed -re "s/\\\\n/\n/g" | 
sed -nre "/^ *(PRIMARY|UNIQUE)? *KEY/ p" |
sed -re "s/PRIMARY KEY/primarykey \`primary\`/" |
sed -re "s/UNIQUE KEY/uniquekey/" |
sed -re "s/KEY/key/" |
sed -re "s/^ *(primarykey|uniquekey|key) \`([^\`]+)\` \((.*)\)( +[a-zA-Z]+)*[,]?$/\1:\2:\3/" |
sed -re "s/\`//g")

# test according to index expression to check

if echo "$HIND" | grep -E "^(key|uniquekey|primarykey).*=" >/dev/null; then
   HINDNAME=`echo "$HIND" | sed -re "s/^(key|uniquekey|primarykey)(.*)=(.*)/\2/"`
   HINDEXPR=`echo "$HIND" | sed -re "s/^(key|uniquekey|primarykey)(.*)=(.*)/\3/"`
   if [ -z "$HINDEXPR" ]; then
      Hindex=`echo "$Hindex" | sed -re "s/(.*):(.*):(.*)/\1:\2=,/"`
      HIND=`echo "$HIND"     | sed -re "s/^(key|uniquekey|primarykey)(.*)=(.*)/\1:\2=/"`
   else
      Hindex=`echo "$Hindex" | sed -re "s/(.*):(.*):(.*)/\1:\2=\3,/"`
      HIND=`echo "$HIND"     | sed -re "s/^(key|uniquekey|primarykey)(.*)=(.*)/\1:\2=\3/"`
   fi
   if [ -z "$HINDNAME" ]; then
      Hindex=`echo "$Hindex" | sed -re "s/(.*):(.*)=(.*)/\1=\3/"`
      HIND=`echo "$HIND"     | sed -re "s/(.*):(.*)=(.*)/\1=\3/"`
   fi
   echo "$Hindex" | grep -i "^$HIND,$"
elif echo "$HIND" | grep -E "^[pt]of.*=" >/dev/null; then
   HCMPMODE=`echo "$HIND" | sed -re "s/^(.)of(.*)=(.*)/\1/"`
   HINDNAME=`echo "$HIND" | sed -re "s/^(.)of(.*)=(.*)/\2/"`
   HINDEXPR=`echo "$HIND" | sed -re "s/^(.)of(.*)=(.*)/\3/"`
   if [ "$HCMPMODE" = "p" -a -z "$HINDEXPR" ]; then
      Hindex=`echo "$Hindex" | sed -re "s/(.*):(.*):(.*)/\2=,/"`
      HIND=`echo "$HIND"     | sed -re "s/^.of(.*)=(.*)/\1=/"`
   else
      Hindex=`echo "$Hindex" | sed -re "s/(.*):(.*):(.*)/\2=\3,/"`
      HIND=`echo "$HIND"     | sed -re "s/^.of(.*)=(.*)/\1=\2/"`
   fi
   if [ -z "$HINDNAME" ]; then
      Hindex=`echo "$Hindex" | sed -re "s/(.*)=(.*)/=\2/"`
      HIND=`echo "$HIND"     | sed -re "s/(.*)=(.*)/=\2/"`
   fi
   if [ "$HCMPMODE" = "p" ]; then
      echo "$Hindex" | grep -i "^$HIND,"
   else
      echo "$Hindex" | grep -i "^$HIND,$"
   fi
else
   Hindex=`echo "$Hindex" | sed -re "s/(.*):(.*):(.*)/\3,/"`
   # ------------------------------------------------------------------------
   # Change interpretation of [tablename:indexexpression]
   # ------------------------------------------------------------------------
   # since 2016-07-21 
   # there exists an index with prefix of indexexpression
   # ------------------------------------------------------------------------
   # before 2016-07-21
   # there exists an index of indexexpression
   # ------------------------------------------------------------------------
   #echo "$Hindex" | grep -i "^$HIND,$"
   echo "$Hindex" | grep -i "^$HIND,"
fi

#

