#!/bin/bash

# check if pip exists

if [ -x /usr/bin/pip ]; then
    /root/zhangh/hmsg inst_pip "pip has been installed" more
    exit 1
fi

# 安装 setuptools依赖包 appdirs
if [ ! -f /root/zhangh/hbox/appdirs-1.4.0.tar.gz ]; then
    /root/zhangh/hmsg inst_pip "No package appdirs-1.4.0.tar.gz in directory /root/zhangh/hbox" more
    exit 1
else
    cd /root/zhangh/hbox
    tar zxvf /root/zhangh/hbox/appdirs-1.4.0.tar.gz
    mv `ls -1d appdirs*/ | sed -n "1 p"` /

    cd /

    python setup.py install
fi

# 安装 setuptools依赖包 packaging
if [ ! -f /root/zhangh/hbox/packaging-16.8.tar.gz ]; then
    /root/zhangh/hmsg inst_pip "No package packaging-1.4.0.tar.gz in directory /root/zhangh/hbox" more
    exit 1
else
    cd /root/zhangh/hbox
    tar zxvf /root/zhangh/hbox/packaging-16.8.tar.gz
    mv `ls -1d packaging*/` | sed -n "1 p" /

     cd /
     cd `ls -1d packaging* | sed -n "1 p"`
     python setup.py install
fi

# 安装 setuptools依赖包 six-1.10.0.tar.gz
if  [! -f /root/zhangh/hbox/six-1.10.0.tar.gz ]; then
    /root/zhangh/hmsg inst_pip No package packaging-1.4.0.tar.gz in directory /root/zhangh/hbox" more
    exit 1
else
    cd /root/zhangh/hbox
    tar zxvf /root/zhangh/hbox/six-1.10.0.tar.gz
    mv `ls -1d six*/` | sed -n "1 p" /

    cd /
    cd `ls -1d six* | sed -n "1 p"`
    python setup.py install
fi

# 安装 setuptools
if  [! -f /root/zhangh/hbox/setuptools-34.3.2.tar.gz ]; then
    /root/zhangh/hmsg inst_pip No package setuptools-34.3.2.tar.gz in directory /root/zhangh/hbox" more
    exit 1
else
    cd /root/zhangh/hbox
    tar zxvf /root/zhangh/hbox/setuptools-34.3.2.tar.gz
    mv `ls -1d setuptools*/` | sed -n "1 p" /

    cd /
    cd `ls -1d setuptools* | sed -n "1 p"`
    python setup.py install
fi

# 安装 pip
if  [! -f /root/zhangh/hbox/pip-9.0.1.tar.gz ]; then
    /root/zhangh/hmsg inst_pip No package setuptools-34.3.2.tar.gz in directory /root/zhangh/hbox" more
    exit 1
else
    cd /root/zhangh/hbox
    tar zxvf /root/zhangh/hbox/pip-9.0.1.tar.gz
    mv `ls -1d pip*/` | sed -n "1 p" /

    cd /
    cd `ls -1d pip* | sed -n "1 p"`
    python setup.py install

    if [ -x /usr/bin/pip ]; then
        /root/zhangh/hmsg inst_pip "Congratulations !!! Python pip is installed Successfully" more
        exit 0
    else
        /root/zhangh/hmsg inst_pip "Sorry !!! Please check again" more
    fi
fi


# 安装 python-devel
yum install python-devel

# 安装 psutil
pip install psutil

# 用于 不同os之间的转化
yum install dos2unix

# install mysql-connector-python
if  [! -f /root/zhangh/hbox/mysql-connector-python-2.2.2.tar.gz ]; then
    /root/zhangh/hmsg inst_pip mysql-connector-python-2.2.2.tar.gz in directory /root/zhangh/hbox" more
    exit 1
else
    cd /root/zhangh/hbox
    tar zxvf /root/zhangh/hbox/mysql-connector-python-2.2.2.tar.gz
    mv `ls -1d mysql-connector-python*/` | sed -n "1 p" /

    cd /
    cd `ls -1d mysql-connector-python* | sed -n "1 p"`
    python setup.py install
    # ? 路径好像有问题
    if [-f /usr/local/lib/python2.7/site-packages/mysql_connector_python-2.2.2-py2.7.egg-info ]; then
      echo "install success!!!" && exit 0
    else
      echo "install failed!!" && exit 1
    fi
fi





