CREATE TABLE `zzz` (
  `hotel_id` BIGINT(20) DEFAULT NULL,
  `accnt_type` CHAR(10) DEFAULT NULL,
  `accnt` BIGINT(20) DEFAULT NULL,
  `balance` DECIMAL(12,2) DEFAULT NULL,
  `accnt_old` VARCHAR(10) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8

