INSERT INTO pos_basecode VALUES (	'pos_bkf_type',	'01',	'客房团队早餐(20)',	'客房团队早餐(20)',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_bkf_type',	'02',	'客房团队早餐(30)',	'客房团队早餐(30)',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_bkf_type',	'03',	'客房会议早餐(20)',	'客房会议早餐(20)',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_bkf_type',	'04',	'客房散客早餐(30)',	'客房散客早餐(30)',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_bkf_type',	'05',	'客房散客早餐(40)',	'客房散客早餐(40)',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'dish',	'-----------------------菜食检查--------------------',	'',	'F',	'F',	800,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'dish0',	'冲菜的理由检查',	'冲菜的理由检查',	'F',	'F',	810,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'dish1',	'检查是否存在未定义项',	'检查是否存在未定义项',	'F',	'F',	820,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'dish2',	'分摊情况的检查',	'分摊情况的检查',	'F',	'F',	830,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'dish3',	'检查套菜明细是否输入',	'检查套菜明细是否输入',	'F',	'F',	840,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'menu',	'-----------------------主单检查--------------------',	'',	'F',	'F',	700,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'menu0',	'主单金额的一致性检查',	'主单金额的一致性检查',	'F',	'F',	710,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'menu1',	'主单日期的一致性检查',	'主单日期的一致性检查',	'F',	'F',	720,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'menu2',	'销单的理由检查',	'销单的理由检查',	'F',	'F',	730,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'menu3',	'联单情况的检查',	'联单情况的检查',	'F',	'F',	740,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'res',	'-----------------------预定检查--------------------',	'',	'F',	'F',	900,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_data',	'res0',	'预付定金情况检查',	'预付定金情况检查',	'F',	'F',910,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pccode',	'-----------------------营业点检查-----------------',	'',	'F',	'F',	500,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pccode0',	'营业点设置常规检查',	'',	'F',	'F',	510,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'plucode',	'-----------------------菜本检查--------------------',	'',	'F',	'F',	100,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'plucode0',	'菜本常规定义检查',	'',	'F',	'F',	110,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'plucode1',	'菜本与营业点的关系检查',	'',	'F',	'F',	120,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'posno',	'-----------------------站点检查--------------------',	'',	'F',	'F',	600,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'posno0',	'站点设置常规检查',	'',	'F',	'F',	610,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pplu',	'-----------------------菜项检查--------------------',	'',	'F',	'F',	300,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pplu0',	'菜项常规定义检查',	'',	'F',	'F',	310,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pplu1',	'菜项的价格定义检查',	'',	'F',	'F',	320,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pplu2',	'菜项与辅料的关系检查',	'',	'F',	'F',	330,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pplu3',	'菜项与打印机的关系检查',	'',	'F',	'F',	340,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pplu4',	'菜项与模式的关系检查',	'',	'F',	'F',	350,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'pplu5',	'菜项与报表数据项的关系检查',	'',	'F',	'F',	360,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'sort',	'-----------------------菜类检查--------------------',	'',	'F',	'F',	200,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'sort0',	'菜类常规定义检查',	'',	'F',	'F',	210,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'sort1',	'菜类与辅料的关系检查',	'',	'F',	'F',	220,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'sort2',	'菜类与打印机的关系检查',	'',	'F',	'F',	230,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'sort3',	'菜类与模式的关系检查',	'',	'F',	'F',	240,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_maint',	'sort4',	'菜类与报表数据项的关系检查',	'',	'F',	'F',	250,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_msg',	'01',	'客人只需付',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_msg',	'02',	'VIP客人',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_check_msg',	'03',	'内部用餐',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dept',	'01',	'服务员',	'Waiter',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dept',	'02',	'收银员',	'Cashier',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dept',	'03',	'厨师',	'Kitchener',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_cancel',	'01',	'输错菜',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_cancel',	'02',	'配料用完',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_cancel',	'03',	'客人退菜',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'0',	'normal',	'normal_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'1',	'c',	'c_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'2',	'co',	'co_eng',	'T',	'F',	0,'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'3',	'赠送',	'赠送_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'4',	'赠送的菜被冲',	'赠送的菜被冲_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'5',	'全免',	'全免_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'6',	'全免的菜被冲',	'全免的菜被冲_eng',	'T',	'F',0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'7',	'单折',	'单折_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'8',	'单折的菜被冲',	'单折的菜被冲_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'A',	'零头',	'odd',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_dish_sta',	'M',	'套菜',	'套菜_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_del',	'01',	'输错单',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_del',	'02',	'练习',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_flag',	'C',	'已上传厨房',	'已上传厨房_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_flag',	'D',	'缺菜',	'缺菜_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_flag',	'M',	'套菜',	'套菜_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_flag',	'O',	'已出菜',	'已出菜_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_flag',	'R',	'还在计时',	'还在计时_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_flag',	'S',	'停止计时',	'停止计时_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_flag',	'T',	'上桌',	'上桌_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_sta',	'0',	'取消',	'取消_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_sta',	'1',	'预订',	'预订_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_sta',	'2',	'登记',	'登记_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_sta',	'3',	'结账',	'结账_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_sta',	'5',	'重结',	'重结_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_menu_sta',	'7',	'删除',	'删除_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'001',	'人民币',	'C01C02C28',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'002',	'港币',	'C29',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'003',	'支票',	'C03C04C07',	'F',	'F',	0,'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'004',	'人民币卡',	'C10C11C12C13C14C15C16C21C25',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'005',	'外汇卡',	'C40C45C50C55C60C65',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'006',	'街账',	'C88',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'007',	'客账',	'C86',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'008',	'赠券',	'C71',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'009',	'冲定金',	'C75',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'010',	'美金',	'C05',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'011',	'早餐券',	'C80',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'012',	'月饼票',	'C72',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sort',	'013',	'礼品券',	'C74',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sta',	'1',	'定金',	'定金_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sta',	'2',	'使用定金',	'使用定金_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pay_sta',	'3',	'结帐',	'结帐_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_pda_reg',	'A',	'A BOX',	'A BOX',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_plu_flag',	'B',	'吧台管理',	'吧台管理_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_plu_flag',	'D',	'一菜多吃',	'一菜多吃_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_plu_flag',	'F',	'早茶',	'早茶_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_plu_flag',	'H',	'海鲜',	'海鲜_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_plu_flag',	'M',	'套菜',	'套菜_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_plu_flag',	'T',	'多吃明细',	'多吃明细_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_plu_flag',	'Z',	'自助餐',	'自助餐',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_print_sta',	'0',	'正常',	'NR',	'T',	'F',	100,	'F',	'F');
INSERT INTO pos_basecode VALUES (	'pos_print_sta',	'1',	'缺纸',	'No Paper',	'T',	'F',	200,	'F',	'F');
INSERT INTO pos_basecode VALUES (	'pos_print_sta',	'2',	'脱机',	'Off Line',	'T',	'F',	300,	'F',	'F');
INSERT INTO pos_basecode VALUES (	'pos_print_sta',	'9',	'其他',	'Other',	'T',	'F',	400,	'F',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_flag',	'C',	'自带烟',	'自带烟_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_flag',	'D',	'自带酒',	'自带酒_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_flag',	'F',	'白鲜花',	'白鲜花_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_flag',	'H',	'横幅',	'横幅_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_flag',	'I',	'FD',	'F',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_flag',	'O',	'FA',	'F',	'F',	'F',	1,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_sta',	'0',	'取消',	'取消_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_sta',	'1',	'预订',	'预订_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_sta',	'2',	'确定',	'确定_eng',	'T',	'F',	0,'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_reserve_sta',	'7',	'登记',	'登记_eng',	'T',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_shift',	'1',	'早市',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_shift',	'2',	'午市',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_shift',	'3',	'午茶',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_shift',	'4',	'晚市',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_shift',	'5',	'宵夜',	'',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'1',	'1 位',	'',	'F',	'F',	10,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'2',	'2 位',	'',	'F',	'F',	11,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'3',	'3 位',	'',	'F','F',	12,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'4',	'4 位',	'',	'F',	'F',	13,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'5',	'5 位',	'',	'F',	'F',	14,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'6',	'6 位',	'',	'F',	'F',	15,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'7',	'7 位',	'',	'F',	'F',	16,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'8',	'8 位',	'',	'F',	'F',	17,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'9',	'9 位',	'',	'F',	'F',	18,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'A',	'A位',	'',	'F',	'F',	22,'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'B',	'B位',	'',	'F',	'F',	23,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'C',	'C位',	'',	'F',	'F',	24,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'D',	'D位',	'',	'F',	'F',	25,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'E',	'E位',	'',	'F',	'F',	26,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'F',	'F位',	'',	'F',	'F',	27,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'G',	'G位',	'',	'F',	'F',	28,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'H',	'H位',	'',	'F',	'F',	29,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'I',	'I位',	'',	'F',	'F',	30,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'J',	'J位',	'',	'F',	'F',	31,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'K',	'K位',	'',	'F',	'F',	32,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_siteno',	'L',	'L位',	'',	'F',	'F',	33,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_special_flag',	'N',	'普通类',	'普通类_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_special_flag',	'S',	'计时类',	'计时类_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_special_flag',	'T',	'特殊类',	'特殊类_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_special_flag',	'X',	'折扣类',	'折扣类_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag',	'0',	'零点',	'零点_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag',	'1',	'团体',	'团体_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag',	'2',	'个人',	'个人_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag',	'3',	'旅行团',	'旅行团_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag',	'4',	'工作餐',	'工作餐_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag',	'5',	'自助餐',	'自助餐_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag1',	'0',	'本地',	'本地_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag1',	'1',	'本省',	'本省_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag1',	'2',	'本市',	'本市_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag1',	'3',	'省外',	'省外_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag2',	'0',	'商务',	'商务_eng',	'F',	'F',	0,	'',	'F');
INSERT INTO pos_basecode VALUES (	'pos_tag2',	'1',	'家庭',	'家庭_eng',	'F',	'F',	0,	'',	'F');
