SELECT * FROM portal.rep_rmsale_new_history WHERE hotel_group_id = 1 AND hotel_id = 5 AND biz_date <= '2015.11.04';
SELECT * FROM portal.rep_rmsale_new;
SELECT DISTINCT biz_date FROM rep_rmsale_new_history WHERE hotel_group_id = 1 AND hotel_id = 5;
DELETE FROM portal.rep_rmsale_new WHERE hotel_group_id = 1 AND hotel_id = 5 AND biz_date = '2015.11.04';
DELETE FROM portal.rep_rmsale_new_history WHERE hotel_group_id = 1 AND hotel_id = 5 AND biz_date <= '2015.11.04';

INSERT INTO portal.rep_rmsale_new
	(hotel_group_id, 
	hotel_id, 
 	biz_date, 
	rep_type, 
	building, 
	CODE, 
	descript, 
	descript_en, 
	rooms_total, 
	rooms_ooo, 
	rooms_os, 
	rooms_hse, 
	rooms_avl, 
	rooms_vac, 
	rooms_sold, 
	sold_fit, 
	sold_fit1, 
	sold_grp, 
	sold_met, 
	sold_gov1, 
	sold_gov2, 
	sold_gov3, 
	sold_ot, 
	sold_ot1, 
	sold_ot2, 
	sold_long, 
	sold_ent, 
	sold_added, 
	rev_fit, 
	rev_fit1, 
	rev_grp, 
	rev_met, 
	rev_gov1, 
	rev_gov2, 
	rev_gov3, 
	rev_ot, 
	rev_ot1, 
	rev_ot2, 
	rev_long, 
	rev_fit_new, 
	rev_fit1_new, 
	rev_grp_new, 
	rev_met_new, 
	rev_gov1_new, 
	rev_gov2_new, 
	rev_gov3_new, 
	rev_ot_new, 
	rev_ot1_new, 
	rev_ot2_new, 
	people_fit, 
	people_fit1, 
	people_grp, 
	people_met, 
	people_gov1, 
	people_gov2, 
	people_gov3, 
	people_ot, 
	people_ot1, 
	people_ot2, 
	people_long
	)
SELECT  hotel_group_id, 
	hotel_id, 
 	biz_date, 
	rep_type, 
	building, 
	CODE, 
	descript, 
	descript_en, 
	rooms_total, 
	rooms_ooo, 
	rooms_os, 
	rooms_hse, 
	rooms_avl, 
	rooms_vac, 
	0, 
	sold_fit, 
	0, 
	sold_grp, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	sold_long, 
	sold_ent, 
	sold_added, 
	rev_fit, 
	0, 
	rev_grp, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	rev_long, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	people_fit, 
	0, 
	people_grp, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0, 
	0
	FROM portal.rep_rmsale_history WHERE hotel_group_id = 1 AND hotel_id = 5 AND biz_date <='2015.11.04';


DELETE FROM  portal.rep_rmsale_new_history WHERE hotel_group_id = 1 AND hotel_id = 5  AND biz_date<='2015.11.04';
	
INSERT INTO portal.rep_rmsale_new_history 
SELECT * FROM portal.rep_rmsale_new WHERE hotel_group_id = 1 AND hotel_id = 5 AND biz_date <='2015.11.04';

DELETE FROM portal.rep_rmsale_new WHERE hotel_group_id = 1 AND hotel_id = 5 AND biz_date <='2015.11.04';

SELECT * FROM portal.rep_rmsale_new_history WHERE hotel_group_id = 1 AND hotel_id = 5 AND biz_date ='2015.11.04' AND rep_type ='B';

SELECT DISTINCT biz_date FROM portal.rep_rmsale_new WHERE hotel_group_id = 1 AND hotel_id = 5 ;

SELECT DISTINCT biz_date FROM portal.rep_rmsale_new_history WHERE hotel_group_id = 1 AND hotel_id = 5 ;
